### ISSUE TITLE
Tabキーでの移動を次のテキストボックスにしてほしい。

### ISSUE THREAD

**Issue by sevenc-nanashi** [Hiroshiba/voicevox#111]
630569e2f46da1956eef35278cc40ee8c3b24495 時点。
読み上げのテキスト入力欄でTabを押す次のテキストでは無く削除ボタンにフォーカスしてしまいます。

**Comment by Hiroshiba** [comment]
@sevenc-nanashi 実は上下キーで移動することができるのですが、Tabキーでの移動の代わりになりそうでしょうか。

**Comment by sevenc-nanashi** [comment]
あ、そうだったんですね（）
ありがとうございました。
