### ISSUE TITLE
Undo/Redoを実装したい

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#116]
今はUndo/Redo機能がないので、行を間違ってdeleteすると、調整結果が消えてしまい、かなりしんどいです。
Undo/Redo機能はユーザーからも期待の声が上がっています。
https://twitter.com/idiotica/status/1427615544300032000

実はVOICEVOXはすでにcommand patternを実装しているので、Undo/Redoがあります。
https://github.com/Hiroshiba/voicevox/blob/630569e2f46da1956eef35278cc40ee8c3b24495/src/store/command.ts#L101-L107
vuexのstateの変更を一部記録しておき、自動的にundo操作を作り出しています。

ただ、stateの変更と、ユーザーが思っているundoがずれていることがよくあります。
たとえば「テキストの変更をundoしたい」場合、「テキストの変更」と「変更されたテキストから得られたイントネーションの変更」の２つのstate変更をundoしたいはずで、このずれを解消するような実装が必要です。

**Comment by Segu-g** [comment]
UNDO/RODOの実装方針についてです。
現在の実装はUNDO/REDOの為のpatchの生成をActionで行っており、これは異なるAction間の順序関係が保証されないのでpatchが壊れてしまいます。UNDO/REDOが正常に動作するためには、シンプルに実装したならば生成時の順序関係が保証されている必要があります。Vuexで生成を順序を保証するためにはActionではなくMutationで操作する必要があります。

Mutationにおいてpatchの生成を正しく行うための実装はいくつか思いつきますがどれが好ましいか意見を聞きたいです。

**Comment by Hiroshiba** [comment]
CommandをActionで管理すべきかMutationにすべきかを考えてもいいかなと思いました。

仰るとおり、コマンドを実装するには、CommandをQueueで管理する必要があると思います。
その方法は大まかに２つあって、１つがmutationのQueueを利用する方法、もう１つがCommand用のQueueを用意しておいてActionで叩くようなラッパーを用意する方法かなと思っています。

提案されているmutationで行う方法の場合、MutationからMutationを叩けないこと（裏技的に叩いた場合はImmerと馴染ませられるかどうか）が課題かなと感じています。
actionを採用する場合は、Queueとの結合をどう実装に落とし込むかが課題になるかなと感じています。

個人的にはAction使うルートのほうが、MutationからMutationを叩く裏技を使わなくていいのできれいかなと感じていますが、Queueを持つ必要があってそれはそれで面倒かなとも感じています。

**Comment by Segu-g** [comment]
MutationからMutationを叩けないというのはcommitできないという意味だと思いますが`MuitationTree<S>`はあくまで`Record<string, (state: S, payload?: any) => any>`なので通常の関数を呼ぶように`this.func(draft, payload)`や`xxStore.mutations.func(draft, payload)`と関数を呼んでも何の問題もないと考えています。
今のように`as StoreOptions<State>`でキャストすると型が消えてしまいプロパティの補完が効きませんが以下のようなラッパーを用いることで型を保持できます。
```typescript
const wrapper = <Arg extends StoreOptions<State>>(arg: Arg): Arg => arg;
export const audioStore = wrapper({
  mutations: {
    [SET_ENGINE_READY](state, { isEngineReady }: { isEngineReady: boolean }) {
      state.isEngineReady = isEngineReady;
    },
    ...
  }
} as const);
```
![image](https://user-images.githubusercontent.com/51497552/130330268-d5d20774-4f1d-4d96-b22d-4c0470c6f7c8.png)

**Comment by Hiroshiba** [comment]
そうです、commitできないという意味でした。
直接叩く場合は、vuexにはmodule機能があって、これを使いたいとなったときに変な挙動しそうだなーとは思ってます。（が、`this.`を使う方針でうまく実装できるならこの問題を無視してそちらの方針で実装して良いと思います。）

**Comment by Segu-g** [comment]
現在用いているStoreは全てglobalなStoreにスプレッド構文で展開しており浅いコピーが入っているので問題ありませんが、Moduleの様に直線参照を渡す必要のあるオブジェクトだと書き換えられないように外部に書いて一度コピーを挟む必要がありそうですね

**Comment by Hiroshiba** [comment]
VuexのModuleはたぶん使わないので、仮にこの方針で行くとしてもモジュールは一旦無いものとしちゃいましょう。

**Comment by Segu-g** [comment]
ImmerとVue3はどちらも変更の検知にProxyを使っているため相性が悪く、ImmerのpoduceWithPatchesでは上手くPatchを生成することができないようです。

**Comment by Hiroshiba** [comment]
なるほどです。
（技術的に興味があり、もしよければ具体的にうまく行かない例orコードを見てみたいです。）

**Comment by Segu-g** [comment]
現在のmainブランチでも発生しており、vuex-loggerを使って確認することができます。実際に発生している例としてはREMOVE_AUDIO_ITEMを実行した時のundo\redoのoperarionはKeyの削除とItemの削除の2つが格納されているはずですがどちらかしか格納されていない筈です（片方はDraftが働かずにproduce内で直接書き換えられている）。
最小化したデモは環境構築が面倒でできていません...😥

**Comment by Hiroshiba** [comment]
なるほど・・・　実際にためてみたら、たしかに２つ目以降の操作が記録されていませんでした。
vue側のproxyをどうにかして外すか、immerをやめるかの２択でしょうか。
vueの実装に依存してしまうという負債を抱えますが、immerをやめるよりは全体の開発工数は少ないかなと思うので、（結構苦渋の決断ですが）この２択なら前者かなと思いました。。

**Comment by Segu-g** [comment]
`JSON.parse(JSON.stringfy(state))`を用いて`state`のスナップショットを撮る事で`Proxy`を外し、immerで正しく`patches`を記録する方法にしました。この方法はコマンド発行毎に`state`全体をコピーするため、`state`が大きくなった時にパフォーマンス上のボトルネックになり得ることを留意してください。プルリクエストのほうにも注意書きを書いておきます。

**Comment by Segu-g** [comment]
`Vue3`の`Proxy`はどうやら外すための`toRaw`関数が提供されているようです！調査不足でした🙇‍♀️
https://v3.vuejs.org/api/basic-reactivity.html#toraw

置き換えてみたところ外見上は問題なく動作しているように感じました。
また、同様にボトルネックになるvuexのloggerプラグイン、`strict`モードを無効化して動作確認したところ、stateの大きさによって重くなっていた動作が改善していました。

**Comment by Hiroshiba** [comment]
！！！　なるほどです、期待です！

**Comment by Hiroshiba** [comment]
テキストを入力した後、AudioQueryなどをfetchしたあとにsetTextが走ることでテキスト欄が一瞬フラッシュする現象が気になっています。
たぶん多くのユーザーが体験する現象なので、リリース前になんとかしたい気持ちがあります。

IMEが入力を開始したことを検知し、確定するまでをpreview状態とできれば、setTextでstateに更新があったときにstateを無視することができるかなと思いました。
もしくは、fetchを実行した後に更にテキストを入力する人は少なそうなので、とりあえずdebouceを外せば軽減できるかなと思いました。

**Comment by Segu-g** [comment]
現在、候補として挙がっている方式を整理します。
+ previewAbleValue
コマンド発行: Enter
Viewにプレビュー用の変数を持たせ、プレビュー中とプレビュー中ではないという状態を持つことで表示する状態を切り替える。プレビューを終えた後に非同期にmutationが走るとその間変更前の状態が見える。その状態で入力してしまうとその前の入力した文字が無駄になってしまう。

+ Buffer + watch
コマンド発行: Enter
Viewに変数を持たせ、watchを使ってstateの状態を監視することで変更を感知する。変更が蓄積されているときはstateを無視する。コマンドが失敗した時にバグる。


+ debounce
コマンド発行: debounce
Viewに変数を持たせ、watchを使ってstateの状態を監視することで変更を感知する。変更が蓄積されているときはstateを無視する。コマンドが失敗した時にバグる。

フラッシュはdebounceがstateに変更を検知した際に、蓄積がないと判定されている(IMEの入力は@updateに通知されない)ため更新が起こってしまい、一瞬再描画が起こっているのだと思います。
Buffer + watch方式でbufferとstateの比較をして、同じ場合は更新しないようにし再描画を抑えられるか試してみようと思います。

**Comment by Hiroshiba** [comment]
> Buffer + watch方式でbufferとstateの比較をして、同じ場合は更新しないようにし再描画を抑えられるか試してみようと思います。

なるほど、すごく良いと思います！！！
