### ISSUE TITLE
日本語が含まれるディレクトリで実行するとエンジンエラー

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#12]

**Comment by yamachu** [comment]
日本語を含むディレクトリでTerminalからrun.exeを叩くことでエンジン側のエラーが再現しました。
そのため、voicevoxのフロントエンド側の問題というよりも、エンジン側の問題のようです。

run.exeをTerminalで叩いてみた時のエラーから、どうも内部で依存しているpyopenjtalkの辞書ファイル読み込みの箇所でクラッシュしているようです（実験を行ったマシン以外からの書き込みのため当該ログを紛失してしましました）。

コードの該当箇所は
https://github.com/r9y9/pyopenjtalk/blob/e5a3ba20f4be0d89216227da0ed4591100f8c4c9/pyopenjtalk/__init__.py#L27

こちらで、日本語を含むパスの場合、日本語を含む `str` に対して `decode('ascii')` をしてしまうためエラーが発生するようです。
他にも対象のファイルに `decode('ascii')` が含まれているため、それらの修正も必要になってくると考えられます。

この事象を解決するため、本家のpyopenjtalkにPRを送っています。
https://github.com/r9y9/pyopenjtalk/pull/15

こちらのPRがmergeされた場合、 https://github.com/Hiroshiba/voicevox_engine 側で最新のpyopenjtalkを取り込み、パッケージングし直すことでこのIssueは修正可能かと思われます。

**Comment by Hiroshiba** [comment]
とても素晴らしいです。原因追求ありがとうございます。
本家pyopenjtalkにマージされたら、貢献者リストに書かせていただきたいのでぜひrequirements.txtを書き換えるプルリクエストを送ってください。
https://github.com/Hiroshiba/voicevox_engine/blob/bb130351f3714e0aa00f3816795c4424a8c1c2a1/requirements.txt#L7

マージされたら僕のWindows環境でもためしてみたいと思います。

**Comment by isnot** [comment]
nice activity 👍
横から失礼します。 

> 手元で確認したいのですが、Windows環境でpyopenjtalkのインストールに失敗し、voicevox_engineのビルドが行えていません…

私も、エンジンの pip install で失敗しました。
requirements.txt にある pyopenjtalk の行は、githubから取得してますが、これを「pyopenjtalk」のみに修正したら、インストールできました。

pipリポジトリにあるバージョンとgithubのHEADで何らかの差異があるのでしょうか。なおこの修正による副作用は未知数です。GUIを electron:serve で起動できて、ざっくりと使えることを確認していますが、コンソールには warning がちょくちょく出ている状態です。

私はPython不慣れのため、外しているかもしれません。
ご容赦ください。

Ubuntu 21.04
Python 3.9
Node.js 14.x
voicevox 0.1.1
 voicevox_engine 0.1.1

**Comment by isnot** [comment]
私の[↑コメント](https://github.com/Hiroshiba/voicevox/issues/12#issuecomment-894501870)について、新しいバージョン0.2.0を使って再度確認しました。
私が確認した問題点としては「pyopenjtalkをpip installするとき失敗する」という部分になりますが、結論としては依存ビルドに必要な、OS側パッケージの不足が原因でした。

いってみれば私のOS環境（Windowsではない）に依存した事柄でした。混乱を招いてしまったようであれば、すみません。
念の為、Ubuntuでの解決方法をメモしておきます。

 $ sudo apt install libatlas-base-dev cmake ninja-build1

https://bbs.avalontech.jp/t/topic/1002/3#post_3 ←こちらでもほぼ同様の事例が書かれていました

**Comment by Hiroshiba** [comment]
エンジン側が最新のpyopenjtalkを使用するようになったので、このissueは解決される見通しです。
次のバージョンアップデート後、実際に日本語ディレクトリで使用可能になっていればCloseします。

**Comment by Hiroshiba** [comment]
解決したので閉じます https://github.com/r9y9/pyopenjtalk/pull/17

**Comment by shigobu** [comment]
バージョン 0.5.0で再発しました。
C:\Users\日本語ユーザー名\AppData\Local\Programs\voicevox を
C:\voicevox へコピーしたら動きました。
フォルダ名を 「C:\ボイスボックス」 へ変更して起動すると、エンジンエラーになりました。

**Comment by Hiroshiba** [comment]
報告ありがとうございます。こちらでも再現できました。
以前とはエラー発声の経路が違っていたこともあり、新しくissueを建てました。
https://github.com/Hiroshiba/voicevox_engine/issues/76
