### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by Patchethium** [Hiroshiba/voicevox#124]
I acknowledged that a new icon could help in the [introducing video](https://www.nicovideo.jp/watch/sm39116000) and made one.
Preview:
![icon](https://user-images.githubusercontent.com/74458240/130013373-d62d9d3a-a892-49b1-9161-89d95b79b5f9.png)
SVG download link: [One Drive](https://1drv.ms/u/s!Al3qk1sl_HQBgUl09pFcTtlA1GXw?e=wBuOme)
This icon stands on V and X in VOICEVOX, representing the concept of audio with spine line and the two characters with color.
Since it's probably not the final version, I opened an issue instead of pull request to allow more discussion about the design.

**Comment by Hiroshiba** [comment]
Thank you!
I've actually received icons and logos from various people, and I was just trying to figure out what to do with them.
I'll refer to your illustrations!
