### ISSUE TITLE
文字列未確定時にマウスカーソルをテキスト欄に乗せたり外したりすると入力文字がロールバックする

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#128]
https://user-images.githubusercontent.com/4987327/130261209-05c93562-c181-4563-8642-453ffc92d954.mp4

ref: https://github.com/Hiroshiba/voicevox/pull/126#issuecomment-902639826

**Comment by Segu-g** [comment]
Vue3の[ドキュメント](https://v3.ja.vuejs.org/guide/forms.html#%E5%9F%BA%E6%9C%AC%E7%9A%84%E3%81%AA%E4%BD%BF%E3%81%84%E6%96%B9)に

>[IME ](https://ja.wikipedia.org/wiki/%E3%82%A4%E3%83%B3%E3%83%97%E3%83%83%E3%83%88%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89)を必要とする言語 (中国語、日本語、韓国語など) においては、IME による入力中に `v-model` が更新を行わないことに気づくでしょう。このような更新にも対応したい場合、 `v-model` をつかう代わりに `input` イベントリスナと `value` のバインディングを使ってください。


と記載があるように@changeやv-modelによる値のバインディングではIMEの未確定な入力は取れないようです。しかし、Q-inputには@inputのイベントが存在しないようなのでQ-inputから変更するかバッファを噛ませるかが必要だと思います。

**Comment by Hiroshiba** [comment]
なるほどです、調査ありがとうございます。`input`イベントがあるんですね、初めて知りました。

q-inputを変えたとしても、VOICEVOXの実装（`setAudioText`）と合うか、将来undo/redoを実装したときに面倒なことにならないかを考えても良いなと思いました。
（実装とは合いそうですが、undo/redoと相性悪い気がするなと思いました。）

**Comment by Hiroshiba** [comment]
#132 がマージされたのでいったんこのissueは解決とします。
