### ISSUE TITLE
「アクセント」と「イントネーション」のタブが横に長くて邪魔

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#14]
横に空間が必要なアクセント修正UIの領域を狭めている。
![image](https://user-images.githubusercontent.com/4987327/127900743-1609d10d-79f3-4484-a125-04fe54c30433.png)

縦にボタンを並べるなどで対応したいが、良いデザインとUIが思い浮かばない。

**Comment by raa0121** [comment]
![image](https://user-images.githubusercontent.com/237271/128382455-2f2de2f2-b1cc-4bba-a00c-d9fca3506734.png)
![image](https://user-images.githubusercontent.com/237271/128382390-bd9c7875-cf92-43a1-b42c-0c82e81416fc.png)
リストにしたら、こんな感じになりますが、いかがでしょうか。

**Comment by Hiroshiba** [comment]
Quasarに変更するプルリク https://github.com/Hiroshiba/voicevox/pull/35 で解決となったのでcloseしたいと思います。

@raa0121 反応できていませんでした、すみません・・・。
