### ISSUE TITLE
インストーラーの挙動で気になったこと

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#148]
* 結合するのOKダイアログは無くても良いかも
  * ユーザーにとって一番いいのは「結合中」もしくは「準備中」ダイアログが表示されて、完了したら消える挙動かなと思います
* ファイルの結合も%TEMP%で行い、かつ完了後にrmしてあげると良さそうです
* 容量はおそらく12GBくらい必要で、容量不足で失敗したことがわかるようなエラーダイアログがほしい
  * ちなみに結合中に落ちた場合は「ショートカット作成エラー」となりました

**Comment by HyodaKazuaki** [comment]
#95 の作成者としてわかる範囲でコメントさせていただきます。

> * 結合するのOKダイアログは無くても良いかも

最初はメッセージボックスを 表示しなかったのですが、データ結合中はしばらくの間なにも表示されなくなるためその確認として表示するようにしました。

対処としては、結合中に「インストールの準備をしています」などのメッセージが付いたInfinite Progress Bar付きダイアログを表示しておくと良いかと思います。
また、ダイアログ上で処理をキャンセルできると便利そうです。
ただ、詳しく調査していませんのでダイアログの詳細についてはわかりかねます。


> * ファイルの結合も%TEMP%で行い、かつ完了後にrmしてあげると良さそうです

データをインストーラと同じディレクトリで結合しているのは、electron-builderで生成される`nsis-web`インストーラの仕様が影響しています。
`nsis-web`インストーラは、同じディレクトリにデータ(7zファイルのこと)があるか確認し、なければGitHub Releaseからダウンロードして、そしてデータを展開するという手順でインストールを実現しているようです。
そのため、結合したデータを%TEMP%に置いた場合、インストーラがデータをまだダウンロードをしていないと勘違いして存在しないデータをGitHub Releaseからダウンロードしようとする可能性があります。
この動作は結合完了後に結合されたデータファイルを削除/リネームすると確認いただけるかと思います。

完了後にデータを削除することは[NSIS custom script](https://www.electron.build/configuration/nsis.html#custom-nsis-script)の`customInstall`項に記述すれば対応できるのではないかと思います。


> * 容量はおそらく12GBくらい必要で、容量不足で失敗したことがわかるようなエラーダイアログがほしい

現時点で、結合中に発生したエラーはハンドリングされています。
https://github.com/Hiroshiba/voicevox/blob/316f0f57f29d192d1723da31f44b79e661daf9d3/build/installer.nsh#L30-L37
`nsis-web`インストーラで細かなところのエラーハンドリングが行われていない可能性があります。

対処として、`FreeDiskSpace`などを使ってディスクの空き容量を確認してから実行するなどが考えられます。

**Comment by Hiroshiba** [comment]
なるほどです、詳細ありがとうございます。
たしかにスクリプト見るとエラーハンドリングされているように見えますね・・・
一旦このままリリースしても良い気がしてきました。

**Comment by HyodaKazuaki** [comment]
#159 で挙動のうち前者2つに対応しました。

以下の点については未対応です。
> * 容量はおそらく12GBくらい必要で、容量不足で失敗したことがわかるようなエラーダイアログがほしい
>   - ちなみに結合中に落ちた場合は「ショートカット作成エラー」となりました

**Comment by Hiroshiba** [comment]
対応ありがとうございます、正常系のUXがだいぶ向上したと思います。
残り１つになったのでissueを作り直したいと思います 🙏
