### ISSUE TITLE
Vuexの厳格モードをONにする

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#153]
v-modelで直接vuexのステートを変更すると、たとえばundo/redoが効かなくなってしまったりするはずです。
vuexの厳格モードをONにしておくと、v-model経由で値が変更されたときにエラーが出るらしいです。
https://vuex.vuejs.org/ja/guide/strict.html

開発モードのときだけこれをONにしても良さそうですが、既存のエラーを洗い出ししないといけないかなと思います。
（ソースコードで`v-model`を検索したら網羅できるかもです）

**Comment by mes51** [comment]
(#126 , #139 のリトライをしようと思いましたが、Undo/Redoがすでに取りかかられているので) こちらの方tryさせていただこうと思ったのですが、1点質問です。
おそらく把握済みだとは思いますが、strictモードをONにする上で、`v-model`を`model-value`に変更していく作業も必要かと思うのですが、単純にこれを行うと、スライダを変更中に今どのくらいの値かがわからなくなってしまう、という問題が起きます。

ex: 話速の変更
https://user-images.githubusercontent.com/936617/130797474-f5c05cab-0796-4b2e-ba1e-152d1f7a0ec0.mp4

これについて、どう対応するかお聞きしたいです。

1. そのまま何もしない
2. 何らか間に別のmodelを挟んでv-modelでバインディング&changeでdispatchを呼ぶ
3. @update:model-valueで変更の度にdispatchを呼ぶ

おそらく2か3のどっちかで、大量のUndoヒストリが積まれるのを許容するかどうかで選ぶ事になるかと思いますが、他に方法があればご教示いただけると助かります

**Comment by Segu-g** [comment]
現在のmainブランチの`crateCommandAction`内や`START_WAITING_ENGINE`内など、`v-model`以外にも`mutation`外でstateを変更してしまっている箇所が存在するようです。後者は修正( #174 )を投げておきました。
