### ISSUE TITLE
読み方を修正可能にする

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#157]
「は」→「わ」や「へ」→「え」など、読み方が意図したものと違うことがあるため、修正可能であることが望まれます
https://twitter.com/dynamo0753/status/1430408473561366528

↓意図してない読み方の例
![image](https://user-images.githubusercontent.com/4987327/130824258-ae65f685-2196-4eb2-b640-4546ed35f85d.png)

「読み方の修正」には次の２種類がありそうです。

1. 読み方をひらがな１文字分だけ変更する
2. ひらがな１文字を２文字以上に変更する

1の実装はデータ構造的にもUI的にも可能そうに思えますが、2はパッと思いつきませんでした。
とりあえず1だけでもあると便利かなと思いました。

要望メモ
https://twitter.com/hoo_tiku/status/1432017720271200256

**Comment by Yosshi999** [comment]
アクセント・イントネーションのところに音素タブを追加してそこにテキスト入力させるのはどうでしょうか
カナ+pau限定にしても音素列とは一対一対応できなかったりしますか

**Comment by Hiroshiba** [comment]
カナ→音素は一部を除いて１：１対応可能です！

一部というのは、無声がありえる「す」とかです。
普通の「す」は「s u」な一方、「～です」の「す」は無声化され「s U」になります。

ジャストアイデアですが、「ス」だったら「s u」、「す」だったら「s U」にする方法があるかもしれません。

**Comment by Yosshi999** [comment]
![image](https://user-images.githubusercontent.com/8027142/131892551-47a5d8a7-2f6f-4596-ad66-80aacb22aacd.png)

UIはこんな雰囲気を想定しています（/で句切り、&でアクセント位置指定）
五十音+αと音素との間の変換規則の実装が面倒そうですね...

**Comment by Hiroshiba** [comment]
なるほど！　すごくよくわかりました。　とてもいいと思います。

記法はsoftalk（ゆっくり、AquesTalk）に慣れている方が多いかもしれません。
https://sosakubiyori.com/softalk-accent/
https://www.a-quest.com/archive/manual/siyo_onseikigou.pdf

五十音→音素はこちらが参考になるかもしれません。
https://github.com/Hiroshiba/julius4seg/blob/master/julius4seg/converter.py
ただ、こちらはopenjtalk用ではなくjulius用の音素なので、少し変更が必要です。

* `:`は伸ばし棒だけどopenjtalkにはないのでリピートする。 例：`a:`→`a a`
* 促音の`q`は`cl`

このあたりは専門知識が必要になりますが、積極的にサポートしたいと思います。
汎用的で便利な修正方法なので、提案してくださったYoshi999さんにぜひ実装をお願いしたいのですが、どうでしょうか。

**Comment by Yosshi999** [comment]
シが二つあるようです...

シ:
```
{
          "text": "シ",
          "consonant": "sh",
          "vowel": "i"
}
```

スィ:
```
{
          "text": "シ",
          "consonant": "s",
          "vowel": "i"
}
```

**Comment by Yosshi999** [comment]
ズィー (http://localhost:50021/audio_query?text=%E3%82%BA%E3%82%A3%E3%83%BC&speaker=1)
```
{
  "accent_phrases": [
    {
      "moras": [
        {
          "text": "ジ",
          "consonant": "z",
          "vowel": "i",
          "pitch": 5.84585428237915
        },
        {
          "text": "イ",
          "consonant": null,
          "vowel": "i",
          "pitch": 5.720374584197998
        }
      ],
      "accent": 1,
      "pause_mora": null
    }
  ],
}
```

ジー  (http://localhost:50021/audio_query?text=%E3%82%B8%E3%83%BC&speaker=1)
```
{
  "accent_phrases": [
    {
      "moras": [
        {
          "text": "ジ",
          "consonant": "j",
          "vowel": "i",
          "pitch": 5.584158897399902
        },
        {
          "text": "イ",
          "consonant": null,
          "vowel": "i",
          "pitch": 5.7834553718566895
        }
      ],
      "accent": 2,
      "pause_mora": null
    }
  ],
}
```

**Comment by Yosshi999** [comment]
↑てっきりopenjtalkの仕様だと思ってたんですがどうやらconsonant+vowel -> textの変換はvoicevox_engineでやっているようなのでそちらでissueたてます

**Comment by Hiroshiba** [comment]
なるほど・・・同じカタカナに投射されるのは把握できていませんでした・・・

**Comment by Yosshi999** [comment]
softtalkを参考に、無音区間無し句切りを`/`, 無音区間あり句切りを`、`, アクセント位置を`'`, 無声化したい場合は音のまえに`_`を置くことにします（カタカナ化は面倒なので`_`が無いときは常に有声とします）

ところで、母音だけの音が無声化されることってありますか？なければそのような表記ははじこうと思っています

**Comment by Hiroshiba** [comment]
> softtalkを参考に、

良いと思います！

> ところで、母音だけの音が無声化されることってありますか？なければそのような表記ははじこうと思っていま

少なくとも関東弁（標準語）は、母音だけの音が無声化することは無いと思います。
ただ、母音だけの音も無声化することができるのであれば、需要は多少あると思います（ひそひそ話など）。

ちなみになのですが、openjtalkにおいて無声化する子音＆母音のペアはかなり限られているはずです。
僕もちゃんと把握していませんが・・・パッと調べた感じ、このリスト？
https://github.com/xmeta/Open-JTalk/blob/e91de139af9ed63f1955093115133b3005c2c90b/src/njd_set_unvoiced_vowel/njd_set_unvoiced_vowel_rule_utf_8.h

が、面倒なので、とりあえず無条件で無声化にすることができて良いんじゃないかなと思います。

p.s.
キ・ク・チ・ツ・シ・ス以外の無声音声は機械学習に用いたデータに存在しないかもしれず、まともな音声が出力されないかもしれません。
実はどんな音声が出力されるのか僕も知らないので、とても楽しみです。
