### ISSUE TITLE
エスケープキーを押すとテキスト欄のフォーカスが外れる

### ISSUE THREAD

**Issue by HyodaKazuaki** [Hiroshiba/voicevox#163]
テキスト欄で文字を入力中にエスケープキー(Escキー)を押すと、該当テキスト欄のフォーカスが外れてしまいます。

例えば、何らかの未確定文字列に対し誤って変換キーを押してしまうと、意図しない変換が行われてしまいます。
変換候補が表示されている段階であれば、エスケープキーを押すことで変換を取り下げることができます。
しかし、VOICEVOXではエスケープキーを押すことでテキスト欄のフォーカスが外れてしまうため、未確定文字列の操作からフォーカスが外れてしまいます。

![out](https://user-images.githubusercontent.com/17569894/130991471-6b7158d6-6355-4223-aabb-7fab3137f8e4.gif)

上のGIF映像にあるように、テキスト欄からフォーカスが外れても文字列は未確定状態が続いているため、再びマウスでフォーカスすることで操作を再開できますが、操作性が悪くなってしまっています。

**Comment by Patchethium** [comment]
After a few minutes of searching I found [KeyboardEvent.isComposing](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing), updated the solution in pull request.

**Comment by HyodaKazuaki** [comment]
Awesome! This is just what I wanted.
