### ISSUE TITLE
音の長さ調整UIをどうするか考える

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#169]
エンジン側に、音素ごとの長さをAudioQueryに含められる機能が実装されました 🎉 https://github.com/Hiroshiba/voicevox_engine/pull/50

音素はローマ字とほぼ１：１対応していて、一応子音と母音それぞれで音の長さを指定することも可能です。
音の長さを調整するUIはどのようなものがいいか、アイデアを募集します。

参考にCevioのUIを紹介します。横方向に時間軸を持つ音素の時系列が表示され、それぞれで長さを調整できる感じです。
（同じ場所で音高も操作できます。）

https://user-images.githubusercontent.com/4987327/131164698-d9d2034b-af85-468d-90d5-86cc43fcd42a.mp4

**Comment by Hiroshiba** [comment]
文の途中の無音の長さも変えたい、という要望をいただきました。
https://twitter.com/shachikuneko000/status/1431808947497803782

**Comment by Hiroshiba** [comment]
要望の声追加 https://twitter.com/sparrow1047/status/1435161241605971973

**Comment by Patchethium** [comment]
I'm surprised that this feature has been hanged so long, I played around a bit and found a possible solution by clipping each of the consonant and vowel sliders:

![スクリーンショット 2021-09-16 100103](https://user-images.githubusercontent.com/74458240/136543209-23278fd5-ca13-4ad1-ad36-a3af93da7407.png)

We can make the left as consonant and right one as vowel length scale, with a maybe 0.5-2 limitation.

This should work without causing too much changes to the existing code, while I still need to clear the layout to fit a new tab, resulting something like this:

![image](https://user-images.githubusercontent.com/74458240/136544006-ea1370c8-fe14-457e-bc7f-c28e6dd85f3a.png)

 So how do you think about it?
