### ISSUE TITLE
読点の前の文字数が2文字以下の場合、その文字の音はスキップして再生されます。

### ISSUE THREAD

**Issue by kokMenteCorp** [Hiroshiba/voicevox#18]
次の文章を入れてみましたが、「こ、こんにちは」と「はい、こんにちは」で「こ」と「はい」の音が再生されません。アクセントのタブで、一度結合し、再度分離すると一応再生されます。

>こんにちは
なんですか急に
挨拶は大事ですよ
こ、こんにちは
はい、こんにちは
ええと、これでいいです？
よろしい、ではコーヒー飲みますか。
飲みたいです、ありがとうございます。
どういたしまして。

![2021-08-03 (12)](https://user-images.githubusercontent.com/85290952/127920624-0e961469-0fc7-41fb-9de4-4d6dc5471f22.png)

**Comment by Hiroshiba** [comment]
ご報告ありがとうございます。

音声合成エンジンの気分により、短い語句は読まれない傾向にあるようです。
この現象はバグというより、現状の音声合成エンジンの仕様になります。

暫定的な対処法ですが、その前にも短い文章を書いておくと、２回目以降は読んでくれることが多いです。
例えば「はい、こんにちは」の場合、「はい、はい、こんにちは」とすると、２回めの「はい」が読まれます。

いずれ改善したいなと考えています。

この仕様はVOICEVOXソフトウェア側からはどうしようもないので、closeしたいと思います。
