### ISSUE TITLE
Android の Termux 上でビルドしようとすると Electron builds are not available on platform: android／Windows 以外での VOICEVOX の動作可否

### ISSUE THREAD

**Issue by neetandgeeks** [Hiroshiba/voicevox#19]
### voicevox
Android の [Termux](https://termux.com/) 上でビルドしようとすると Electron builds are not available on platform: android となり、ビルド出来ません。voicevox_engine に対する、VS Code における [code-server](https://github.com/cdr/code-server) のようなクライアントがあると有り難いです。

<img src=https://user-images.githubusercontent.com/85488234/128127166-cc5d814e-097e-413c-b4d0-010fec5e7f93.png width="320px">

<img src=https://user-images.githubusercontent.com/85488234/128127164-07d09643-ad76-483f-9855-feb74df056dc.png width="320px">

※ [gpm install](https://github.com/neetandgeeks/Toybox/blob/main/Screenshot_20210803-153845.png) 及び yarn でやってみました。

※ [Termux における code-server のビルド](https://dev.to/codeledger/how-to-get-visual-studio-code-to-run-in-termux-on-android-405j)

※ [Android support · Issue #9162 · electron/electron](https://github.com/electron/electron/issues/9162)

※ 追加でインストールしたもの
```git nodejs yarn```

### voicevox_engine
一方、voicevox_engine は Termux 上で問題なくビルド出来ました。

<img src=https://user-images.githubusercontent.com/85488234/128127308-39515b88-7562-4bf3-ab9c-d44f48eeb6ce.png width="320px">

※ 追加でインストールしたもの
```git python cmake ninja```

### 補足
[ARM な Windows 向けに VOICEVOX をビルド](https://www.electronjs.org/docs/tutorial/windows-arm)出来れば [Android 上の Wine](https://dl.winehq.org/wine-builds/android/) で動かせるかもしれません。試してみます。

※ x86_64 環境では、先に run.exe を走らせる必要があったりと少し工夫が要りますが、voicevox、voicevox_engine 共に [macOS](https://github.com/Gcenx/homebrew-wine) や Linux の Wine で動作させることが出来ました（どちらの環境でもソースからネイティブ版をビルド出来るので余り意味はないかもしれません）。

**Comment by neetandgeeks** [comment]
```set npm_config_arch=arm64``` してソースのインストールを試みるとダウンロードが ```[1439/1475]``` より先に進みませんでした。

そこで一旦 Wine を諦めて code-server のソースディレクトリを覗くと、なんとなく lib/vscode 以下に配した vscode のソースの Chromium 担当部分を http サーバで代替しているように見えます。

https://github.com/cdr/code-server
https://github.com/cdr/code-server/tree/main/lib/vscode
https://github.com/cdr/code-server/blob/main/typings/pluginapi.d.ts

詳しい皆様後は任せたー。とはいえ言い出しっぺなので、自分の方でも lib/vscode 以下を voicevox で置き換えて動くものが出来ないかちょっと試してみます。お騒がせしました。

**Comment by neetandgeeks** [comment]
code-server のコードを眺めました→手に負えないということが分かっただけでした。Python ならいくらか読み書き出来るので Pydroid 3 辺りを使ってそれっぽいクライアント GUI を書いてみます。

**Comment by neetandgeeks** [comment]
Android ではない上にクライアント GUI というかクライアント CLI もどきですが、voicevox_engine とやりとり出来ました。とりあえずは解決ということで。

素晴らしいソフトウェアをオープンソースとしてリリースして下さいましたことに感謝します。

![2021-08-06-185500_849x457_scrot](https://user-images.githubusercontent.com/85488234/128494857-6e42a1d3-2cff-47de-a4c7-ac50b6a418e8.png)

![2021-08-06-185205_1280x740_scrot](https://user-images.githubusercontent.com/85488234/128494882-31a69fa8-5a48-41ee-963a-02014ebdf1a3.png)

```python3
from telnetlib import Telnet
with Telnet('localhost', 50021) as tn:
    tn.write(b"GET /version HTTP/1.1\n")
    tn.write(b"Host: localhost\n")
    tn.write(b"\n")
    tn.write(b"POST /audio_query?text=&speaker=0 HTTP/1.1\n")
    tn.write(b"Host: localhost\n")
    tn.write(b"\n")
    tn.write(b"POST /accent_phrases?text=%E3%81%82&speaker=0 HTTP/1.1\n")
    tn.write(b"Host: localhost\n")
    tn.write(b"\n")
    print(tn.read_all().decode('utf8'))
```

```python3
import requests
import urllib.parse
urllib.parse.quote("ア")
payload='{"accent_phrases":[{"moras":[{"text":"%E3%82%A2","vowel":"a","pitch":6.5}],"accent":1}],"speedScale":2,"pitchScale":0.15,"intonationScale":2}'
payloadlength=str(len(payload))
headers={'Host': 'localhost', 'content-length': payloadlength, 'content-type': 'application/json'}
r=requests.post("http://localhost:50021/synthesis?speaker=0", headers=headers, data=payload)
```

#### 参考文献
https://github.com/Hiroshiba/voicevox_engine/blob/master/run.py
https://docs.python.org/ja/3/library/telnetlib.html
https://docs.python-requests.org/en/master/user/quickstart/

#### macOS（intel）／Linux（x86_64）／Android の VOICEVOX と VOICEVOX_ENGINE

|OS|VOICEVOX|VOICEVOX_ENGINE|
|---|---|---|
|macOS（intel）| ソースからビルドして OS Native 版が動作 | Wine ＋ Windows 版 ENGINE |
|Linux（x86_64）| ソースからビルドして OS Native 版が動作  | Wine ＋ Windows 版 ENGINE |
| Android（ARM64） | 互換クライアントの自作で対応可能 | リモートの Windows 版 ENGINE |

**Comment by neetandgeeks** [comment]
https://twitter.com/hiho_karuta/status/1423135372226097163
↑
ということで、勝手に閉じない方がよさそうなのでリオープン。

自分的には Android で使える WebUI が欲しいです。

**Comment by Hiroshiba** [comment]
いったんPCでの開発に注力したいので、こちらのissueは閉じます。
（閉じても検索にはヒットするので、次に同じことをされる方の参考になると思います。）

もしよろしければ、AndroidでVOICEVOXを利用されたい動機を伺いたいです。

**Comment by neetandgeeks** [comment]
ありがとうございます。動機についてはユーザー側と開発者側の二側面あります。

#### ユーザー側
単純にスマートフォンは利用者が多いので、iPhone や Android で VOICEVOX が動けばこのソフトを使える人口が増えるのではないかというのが一点。もう一点は個人的な理由となりますが、タブレットやスマホはPCに比べ持ち運びやすいので、寝転がりながらその時思いついたコントを音声合成したりといったカジュアルな使い方をしたいことが挙げられます。

#### 開発者側
自分は現在、個人開発でオープンソースハードの空気圧駆動パワードスーツや知能義肢（ウェアラブル PC や AI アシスタントのようなものを内蔵する義肢を想定）を作ろうとあれこれ計画／開発しているのですが、そのアシスタントシステムの音声入出力の出力側でこちらのソフトを使いたいと考えています。パワードスーツや義肢に対しての指示や応答はキーボードを叩いてのようにはいかず、音声コマンドや、スマートグラス等を併用しての視線入力がメインになると予想される為、音声入出力の優先順位は上位にあります。

実際に用いる ARM64 デバイスのプロトタイピングを行う際、Android 上で動作する開発環境こそ限定されるものの、バッテリーも画面もネットワークも一式揃っている為、スマホ等の Android 端末は便利です。今後も Termux 上で VOICEVOX_ENGINE のビルドが通る場合、VOICEVOX がそのまま動けば将来こちらをベースにパワードスーツや知能義肢のアシスタント AI を作れたら面白そうだと考えておりました。

**Comment by Hiroshiba** [comment]
ありがとうございます。
スマホで音声合成したいという需要はほとんど聞かないのですが、タブレットだと違うかもしれませんね。
開発者視点でのモチベーションも非常によくわかりました。
ありがとうございます！
