### ISSUE TITLE
アクセントを変更しても、調整済みのイントネーションを変えないようにする

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#196]
## 内容

イントネーションを調整した後にアクセントを変更すると、そのアクセント句以外のイントネーションもすべてリセットされます。

### Pros 良くなる点

アクセント変更後にイントネーションを再調整する必要がなくなる

### 実現方法

アクセントを変え、かつそのアクセント句以外でイントネーションを調整していた場合、調整済みのイントネーションは残す？

## その他

イントネーションのリセットが入るのは、「テキストを変更した時」「アクセントを変えた時」「アクセント句を結合した時」「アクセント句をsplitしたとき」です。
そのいずれでも、調整済みイントネーションがあって同じような読みだった場合はイントネーションを残す処理ができると最高だと思いますが、これは実装がむちゃくちゃ大変だと思います。

要望の声　https://twitter.com/sparrow1047/status/1435161241605971973

**Comment by y-chan** [comment]
これ、思ったんですが、アクセント系を操作したときに`FETCH_MORA_PITCH`を変更しないようにするだけではだめなんですかね...?

**Comment by Hiroshiba** [comment]
それだと、アクセントを変えても全く同じ音声が返ってくると思います。

**Comment by Hiroshiba** [comment]
テキストを変更した時にはアクセントが変わってしまいますが、そちらはあまりにも難しいのと、アクセントを変更してもイントネーションが変わらないようになったので、このissueは閉じたいと思います。
