### ISSUE TITLE
store周りの型について

### ISSUE THREAD

**Issue by y-chan** [Hiroshiba/voicevox#197]
## 内容

store.dispatchなどで型補完が微妙なのが悲しい
Vuexの仕様として仕方ないのかもしれないが、型が無いのは不便なので、超面倒ではあるが型情報を丁寧に整備したい

### Pros 良くなる点

TypeScript的に扱いやすさが向上し、dispatchでの値の渡し間違いなどを防げる

### Cons 悪くなる点

コードが分散してしまうかもしれない(storeにpayloadとして書き込んでいる型情報を移動させるので、見やすさが少々失われる...?)
このプロジェクト用にStoreを拡張することになるので、汎用的実装ではない

### 実現方法

Vuexで元からある型情報を拡張し、より精密な型情報を書き込む

## VOICEVOXのバージョン

0.5.0以降...?

## その他

私自身、Vuexを用いた開発経験はなくTypeScriptやNuxtで作られたプロジェクトに貢献したことがある程度なので、ここら辺に強い方々が解決するのが良策かもしれません...w
どうやら[型情報強化に関するPR](https://github.com/vuejs/vuex/pull/1953)が出ているようで、こういうのを待つというのも手かもしれません

このプロジェクトの方向性として、手動で実装してしまっても良いのか、放置して緩い型でやっていくのか、などの点から議論していく場になればなと思っています。

**Comment by Hiroshiba** [comment]
Vuexのaction/mutationで型が消えるのは僕も苦しんでいるので、可能であればなんとかしたいとは感じます。
ただ、たぶんかなりのTypeScript力が必要なので、とても難しいんだろうなと感じています。

どういう方法があるか議論、もしくは誰かできる人がいたらおまかせしたいです。

**Comment by y-chan** [comment]
@Hiroshiba まだ未改善なので再オープンしていただけますかね...?(ミスでcloseに紐づけてしまっていた...)

**Comment by Hiroshiba** [comment]
おっと、了解です！
