### ISSUE TITLE
Issue Templateの改善

### ISSUE THREAD

**Issue by y-chan** [Hiroshiba/voicevox#198]
## 内容

予め書かれている括弧書きのコメントを消し忘れてしまうことがあるので、HTML記法(`<!-- -->`)でコメントアウトしておきたい(Issue Template的には編集時のみ見え、Issueとして投稿した際には見えないという挙動を望む。消しても消さなくてもどちらでも良いという形が取れる)

### Pros 良くなる点

コメントを消す作業が不要になり、誤って予め書かれていたコメントが投稿されることが防げる

### Cons 悪くなる点

何も書かれていない小見出しが生まれる可能性がある

### 実現方法

括弧書きコメントをHTML記法でコメントアウトする

## その他

こちらで良さそうならEngine側にも適用します。
あと、Issue Templateとは別ですが、Pull Request Templateもあってもいいかもしれませんね

**Comment by Hiroshiba** [comment]
なるほど、良いと思います！アサインします。
