### ISSUE TITLE
テキスト欄の消去方法がわかりづらい

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#20]
テキスト欄を空白にした後、もう一度消去を押せばテキスト欄を消去できるけど、かなりわかりづらいのでなんとかしたい。

関連 #13

**Comment by Hiroshiba** [comment]
個人的には、テキストボックスにマウスカーソルを合わせると右にゴミ箱ボタンが出てきて、それをクリックすると消去できるというUIが良いと思っています。

**Comment by raa0121** [comment]
実装できました。いかがでしょうか。

https://user-images.githubusercontent.com/237271/128185195-da0f03c9-6f17-4fd0-b759-332238ba7882.mp4

**Comment by Hiroshiba** [comment]
すごく良いですね！　プルリクエストの方でコメントしました。

**Comment by Hiroshiba** [comment]
次バージョンでわかりやすくなる見込みです。
