### ISSUE TITLE
プロジェクトの新規作成メニューがほしい

### ISSUE THREAD

**Issue by HyodaKazuaki** [Hiroshiba/voicevox#200]
## 内容

ファイルメニューにはプロジェクトやテキストを開いたり書き出したりする機能が備わっているが、プロジェクトを新規作成するメニューが存在しない。
VOICEVOXを起動したまま新たにプロジェクトを作りたい場合があるので、ファイルメニューに「新規作成」ボタンを追加してほしい。

### Pros 良くなる点

新規プロジェクトを作成するために度々VOICEVOXを起動し、エンジンの起動完了を待つ必要がなくなる。

### Cons 悪くなる点

特になし

### 実現方法

* 空っぽのプロジェクトファイルを読み込むような挙動を実現する
ref. #11

## VOICEVOXのバージョン

0.5.0

## OSの種類/ディストリ/バージョン

Windows 10 Home 64bit (20H2 Build 19042.1165)

## その他

(関連して何か気がついたこと、気になることがあればココに書いてください)

**Comment by Hiroshiba** [comment]
なるほど！　課題と解決策がとてもわかりやすいと感じました。

@HyodaKazuaki もしよかったら実装に挑戦してみませんか？
リポジトリの構成などで分かりづらい点があれば紹介します！

**Comment by HyodaKazuaki** [comment]
> もしよかったら実装に挑戦してみませんか？
リポジトリの構成などで分かりづらい点があれば紹介します！

ありがとうございます。
早速PRを作成しましたので確認をお願いします。
#202
