### ISSUE TITLE
日本語パスでエンジンエラーになる

### ISSUE THREAD

**Issue by shigobu** [Hiroshiba/voicevox#203]
## 不具合の内容

v 0.5.0を日本語ユーザーでインストールすると、起動後にエンジンエラーが表示される。
「C:\voicevox」へコピーしてから起動するとエラー出ない。
「C:\ボイスボックス」に変えるとエラーが出る。

### 現象・ログ

v 0.5.0を日本語ユーザーでインストールすると起動時にエンジンエラー
コマンドプロンプトからrun.exeを起動させるとエラーメッセージが表示される。
```
Traceback (most recent call last):
  File "C:\ボイス~1\run.py", line 257, in <module>
  File "C:\ボイス~1\run.py", line 61, in make_synthesis_engine
  File "core.pyx", line 6, in core.initialize
  File "core.pyx", line 14, in core.initialize
AssertionError
```

### 再現手順

日本語を含むユーザーでインストールする。
あるいは、日本語フォルダへコピーする。

VOICEVOXを起動する。

### 期待動作

日本語を含むパスでも起動できるようにする。

## VOICEVOXのバージョン

0.5.0

## OSの種類/ディストリ/バージョン

Windows 10 Home
20H2

**Comment by Hiroshiba** [comment]
報告ありがとうございます。
このエラーはエンジンのエラーなので、エンジンのリポジトリのissueで取り扱いたいと思います。
https://github.com/Hiroshiba/voicevox_engine/issues/76

（すみません、新たなissueに気づかず別で建ててしまいました）

**Comment by Hiroshiba** [comment]
0.5.2で解決されたはずなのでclose
