### ISSUE TITLE
VOICEVOXのLinux用実行バイナリを作る

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#218]
## 内容

VOICEVOXのコアライブラリが公開されました。 https://github.com/Hiroshiba/voicevox_core
これでLinux版のVOICEVOXを作成できるはずです。

このタスクは非常に長くなると思われます。
ちょっとでも取り掛かった方がいたら、ぜひコメントで知見ややり方を共有して頂けると・・・！

## OSの種類/ディストリ/バージョン

*   Linux

**Comment by aoirint** [comment]
Linux版VOICEVOXの配布方法の候補は、zip配布、deb/rpm、PPA=Ubuntuの非公式パッケージリポジトリ、AppImage、snap、flatpakが考えられるかなと思っています。

Ubuntuを使っていてよく見るのはdebとAppImageです。
わたしは、どれも作成や特性の知見がないので、VOICEVOXでは使えないものもあるかもしれません。

Electronの例だと、
[atom/atom](https://github.com/atom/atom) 、[VSCode](https://code.visualstudio.com/download)はdeb/rpm、
[laurent22/joplin](https://github.com/laurent22/joplin) はAppImageを採用しているようです。

**Comment by Hiroshiba** [comment]
なるほどです！　`deb/rpm`か`AppImage`が良さそうですね。
electron-builderを見るに、どれでも選択できそうでした。
https://www.electron.build/index.html

個人的には、GUIを使うユーザーにとってわかりやすいものが良いかなと思っています。

**Comment by aoirint** [comment]
`AppImage` で進める形で取り組んでみようかと思っています。

**Comment by aoirint** [comment]
`AppImage` を選ぶ場合、配布の方法として、2つの候補を考えています。

- `AppImage` にVOICEVOX フロントエンド（このリポジトリ）と、VOICEVOX ENGINEをまとめて、圧縮分割する
- `AppImage` にはVOICEVOX フロントエンドの実行用バイナリのみを格納する。あとから追加で、圧縮分割されたVOICEVOX ENGINEをダウンロードする

**Comment by aoirint** [comment]
`deb` を選ぶ場合、Makefileから簡単にdebパッケージを作ることができるようです。

- https://qiita.com/myoshimi/items/6375b76de5f0a98a2c41

## Makefile

```make
#!/usr/bin/env make

.PHONY: all
all:
	mkdir -p build
	wget -O build/index.html https://www.example.com/

.PHONY: install
install:
	mkdir -p /opt/myexample
	cp -r build/ /opt/myexample

.PHONY: uninstall
uninstall:
	rm -rf /opt/myexample

.PHONY: clean
clean:
	rm -rf build/
```

## コマンド

```shell
sudo apt install checkinstall

make

sudo checkinstall --install=no --pkgname=myexample --pkgversion=0.1.0

ls | grep .deb
# myexample_0.1.0-1_amd64.deb

make clean

sudo dpkg -i myexample_0.1.0-1_amd64.deb
```

**Comment by Hiroshiba** [comment]
> AppImage を選ぶ場合、配布の方法として、2つの候補を考えています。

ユーザーが１つだけ操作を行えばVOICEVOXが使えるようになるのが良いのかなと思っています。（windowsの場合はインストーラーのダブルクリック）
同じような形式にできれば、まとめて配布でも分割配布でもどちらも良いなと思いました。

**Comment by aoirint** [comment]
`AppImage` にVOICEVOX ENGINEを同梱した形で配布できそうです（ #265 を取り込めば `run` も実行できそうです）。

`AppImage`の場合、Release上では、7zで圧縮分割した状態で配布し、
ユーザ側で1つ1つダウンロードすることにはなるのかなと思っていますが、
ファイルをそろえて展開すれば、実行可能なAppImageファイルを取得できます。

もしくは、インストール用のスクリプトを用意することになるかな、と思っています。

アプリケーション一覧に登録するには、$HOME/.local/share/applicationsのようなディレクトリに
`*.desktop` ファイルを追加する必要があります。
しかし、Electron Builder 21以降は、そのような機能がないようなので、
VOICEVOX側で実装するか、インストールスクリプトが必要になるように思っています。

- https://www.electron.build/configuration/appimage.html

> Since electron-builder 21 desktop integration is not a part of produced AppImage file. AppImageLauncher is the recommended way to integrate AppImages.


ちなみに、Ubuntuでは、`p7zip-full`パッケージをインストールしておく必要はありますが、
GUI上で圧縮分割ファイルの展開ができました。

![voicevox_linux_cpu_7z_volume](https://user-images.githubusercontent.com/27213639/134750187-d492e118-598f-4e2c-90d8-26e50c3aa45d.png)

**Comment by Hiroshiba** [comment]
どういう配布形式が良いのか全く検討つかなくて判断が難しいですね・・・

一旦用意が簡単な方法で配布してみて、ツイッターなどで反応を確かめてもいいかなと思いました。
なので手っ取り早そうな方法でやってみるのはどうでしょう。
個人的にはなんとなく、 @aoirint さんの言及にあるインストールスクリプトの用意が簡単そうだなと感じました！

**Comment by aoirint** [comment]
メモ

#270 で、Linux版VOICEVOX終了時 `app.on("quit", ...)` 、ENGINEのプロセスが終了されない問題が起きています。

`background.ts` の [pkrumins/node-tree-kill](https://github.com/pkrumins/node-tree-kill) でプロセスキルする部分が関係していて、Linux・macOS上で問題が起きると思っています。

TreeKillは、 `child_process.spawn` を使って `ps` コマンドを実行し、
killすべきプロセスIDリストを取得する実装になっていますが、試したところ、
ChildProcessのコールバック `ChildProcess.on("close", ...)` がなぜか呼び出されず、
プロセスIDリストが返ってこないため、ENGINEのプロセスがkillされないという状態のように思いました。

- https://github.com/pkrumins/node-tree-kill/blob/cb478381547107f5c53362668533f634beff7e6e/index.js#L97-L117
    - https://github.com/pkrumins/node-tree-kill/issues/27
    - https://github.com/pkrumins/node-tree-kill/issues/28
- https://nodejs.org/api/child_process.html#child_process_class_childprocess

Node.jsのリポジトリにも過去に似た問題が報告されていそうでしたが、同じ問題かはわかりません。

- https://github.com/nodejs/node/issues/4500#issuecomment-288599878

一応、tree-killのコードを書き換えて、`child_process.spawn` の代わりに `child_process.spawnSync` を使った同期実行にすると解消するようでした。

また、tree-kill の代わりに、 `process.kill` でENGINEのPIDをkillしても解決するのかなと思っていますが、孫プロセス（ENGINEの子プロセス）がkillできないということがあるのかな、とも思っています。

**Comment by Hiroshiba** [comment]
報告ありがとうございます！
なるほど…プロセス周りのことはよく知らないのですが、マルチプラットフォームで同じように動く実装にしたいですね…

でもいい感じの方法が思いつかないので、ワークアラウンド的にwin以外の場合は普通にkillを実行しても良い気がしました。

**Comment by aoirint** [comment]
#282 のパッチで解決すると思います。
Linux・Windowsで動作確認しています。

ENGINEのプロセスが終了するまでVOICEVOXのプロセス終了を待機させる方法（ `app.on("before-quit", ...)`で停止処理をする方法）で実装しています。

ログ出力まわりの整理 #280 や、ENGINEのログを確認できるようにする #281 を合わせて送っています。

**Comment by Hiroshiba** [comment]
可能なら、tar.gz形式のvoicevoxバイナリもダブルクリックで実行可能にしたいところなのですが、ダブルクリックしても実行できない問題はそもそもどんな感じですか・・・？
もしライブラリのパスが見つからないためであれば、こちらのコメントでもしかしたら修正可能かもと思いました。
https://github.com/Hiroshiba/voicevox/pull/270#issuecomment-932898602

**Comment by aoirint** [comment]
> ライブラリのパスが見つからない

いえ、共有ライブラリではなく、UbuntuのファイルエクスプローラであるNautilusの挙動が問題ですね。

ターミナルから実行すると、tar.gzから展開したVOICEVOXを起動することができます。

```shell
$ **/linux-nvidia-prepackage-targz/VOICEVOX/voicevox
[02:11:19.186] [info]  Starting ENGINE in GPU mode
[02:11:19.676] [error] Error: Failed to fetch Failed to fetch AudioQuery for the text "".
[02:11:19.683] [error] TypeError: Failed to fetch
[02:11:20.651] [info]  waiting engine...
[02:11:21.652] [info]  waiting engine...

...
```

ダブルクリックで実行しようとするには、わたしの環境（Ubuntu 20.04, GNOME nautilus 3.36.3）では、
以下のような準備が必要でした。

- `voicevox`ファイルを右クリックする
- ファイルを開く方法の選択ダイアログを開く
- `Run Software`を選択する

その上で実行しようとすると、Nautilusのログに以下のように表示され、起動しませんでした。Electronのプロセスがそもそも立ち上がりません。なにかファイルシステムが仮想化されていそうです。

```
** (nautilus-autorun-software:***): WARNING **: ***: Unable to find device for URI: Containing mount for file /home/***/voicevox not found
```

`*.desktop`ファイルをダブルクリックして実行するようにすることもできそうで、こちらが有力なのですが、同じように起動しませんでした。

```
** (nautilus-autorun-software:***): WARNING **: ***: Unable to find device for URI: Containing mount for file /home/***/voicevox.desktop not found
```

Nautilusの`*.desktop`ファイルの取り扱いや、実行ファイルのダブルクリック実行の挙動は安定していない印象があります。

まだ調査が必要そうです。

Nautilusのログ確認用コマンド

```shell
killall nautilus
G_DEBUG="all" NAUTILUS_DEBUG="All" nautilus
```

**Comment by aoirint** [comment]
デスクトップ（$HOME/Desktop/）に`*.desktop`ファイルをコピーした上で、右クリックメニューから`Allow Launching `を選択することで、ダブルクリックから起動できました。

![04_04_10_2021_03_12_26](https://user-images.githubusercontent.com/27213639/135766302-ce0b08b8-27b3-43d4-bc95-df64ed013ecd.png)

![20 04_04_10_2021_03_12_12](https://user-images.githubusercontent.com/27213639/135766304-68e727dc-282d-4b79-9549-0ad2a1ba03ce.png)

```desktop
[Desktop Entry]
Name=VOICEVOX
Exec=/path/***/voicevox/voicevox
Terminal=false
Type=Application
Icon=/path/***/voicevox/voicevox.png
StartupWMClass=VOICEVOX
Categories=AudioVideo;
```

**Comment by Hiroshiba** [comment]
おーなるほどです！！！
ユーザー向けにどう案内しようか悩みますね・・・

確認なのですが、AppImageインストーラー版はアイコンをダブルクリックすることでVOICEVOXを起動可能、という認識で合っていますか？
であれば、一旦解決策がわかるまでインストーラー版だけ出して、tar.gz版はissueを建てて調査というのでも良いのかなと思った次第です。

**Comment by aoirint** [comment]
> AppImageインストーラー版はアイコンをダブルクリックすることでVOICEVOXを起動可能

はい、
AppImageインストーラ版は、アイコンの（シングル）クリックで起動可能です。

WIndowsのスタートメニューに相当する場所に登録されるので、そこから起動する形です。

- https://help.ubuntu.com/stable/ubuntu-help/gs-launch-applications.html

ちなみにAppImage単体は、実行権限を与えれば、ファイルエクスプローラからダブルクリックで起動可能です。
いま気づきましたが、tar.gzでなくて、分割されていないAppImageの配布でもいいのかもしれません..
ただ、Artifactでは linux-{cpu,nvidia}-appimage ですが、CPU版のAppImageビルドは、Windowsに合わせてコメントアウトしています（コメントアウトを解除すれば動くはずです）。

**Comment by Hiroshiba** [comment]
> tar.gzでなくて、分割されていないAppImageの配布でもいいのかも

確かに！！　それが一番手っ取り早い上にユーザーにとってもわかりやすい気がしました。

CPU版のAppImageもせっかくなので作っておくと喜ばれそうだと思います。
