### ISSUE TITLE
VOICEVOXにスタイル音声合成を追加する

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#229]
VOICEVOXには四国めたん・ずんだもんの２キャラクターがいますが、実はそれぞれにちょっとスタイルの違う感情音声が３つずつあります。
その感情音声（スタイル）の、まあまあ良い機械学習モデルができたので、バージョン0.6.0か0.7.0のアップデートで迎えたいと思っています。

スタイル音声はこれくらい変わります。上から順に四国めたんのノーマル・あまあま・セクシー・ツンツン、ずんだもんのノーマル・あまあま・セクシー・ツンツンです。

https://user-images.githubusercontent.com/4987327/134549931-ffb8a3e1-9318-4ec2-9038-28cd4ee9a7d7.mp4

（今のVOICEVOXの音声は四国めたん・ずんだもんのあまあまです。）

このタイミングで、ソフトウェア・エンジン・コアに散らばっているキャクター情報を、こうまとめていきたいです。
<img src="https://user-images.githubusercontent.com/4987327/133295096-06b30579-8ced-449c-a184-5ca49906e742.png" width="400">

* エンジンはキャラクター情報を一切持たず、コアの情報を素通りさせます
* ソフトウェアは最低限の情報（名前やサムネ画像）だけを持ちます
* コアが持つ情報とソフトウェアが持つ情報は、IDによって決定します

変更したい箇所は次のとおりです。

- [x] 必須（0.7.0に含めたい）
  - [x] コア
    - [x] バージョン・スタイル・IDのメタ情報を追加（0と1は過去のと互換性があるようにします）
      - [x] ubuntu18環境でビルドする
  - [x] エンジン
    - [x] https://github.com/Hiroshiba/voicevox_engine/issues/90
    - [x] スタイルなどが追加されたコアに対応
    - [x] 情報をFastAPIのModelに入力していく（OpenAPI用の型付け）
  - [x] ソフトウェア
    - [x] AudioItem.characterIndex　→　AudioItem.speakerに変更
    - [x] 0.7.0に向けてprojectファイルのマイグレーション
- [ ] 0.7.0には必須ではないが必要なもの（0.8.0か0.7.1に含めたい）
  - [x] #312
    - CharacterInfo.metas.speaker　→　speakerUuid、styleId
    - characters/dummy1/metas.jsonのspeaker　→　speakerUuid、styleId
    - AudioItem.speaker　→　speakerUuid、styleId
  - [x] #313
  - [x] https://github.com/Hiroshiba/voicevox/issues/293
- [ ] いつかやりたいこと
  - [ ] 話者情報をエンジンから取ってくる
    -  characters/dummy1/metas.jsonからstyleIdを消去
    - エンジンの情報をもとにCharacterInfoを変更（スタイル１つにつきCharacterInfoを１つ作成）

（見逃しがあればご指摘ください）

**Comment by Hiroshiba** [comment]
VOICEVOX 0.6.0から、speakers情報がこう変わっているはずです。
```json
[
  {
    "name": "四国めたん",
    "styles": [{ "name": "ノーマル", "id": 0 }],
    "speaker_uuid": "7ffcb7ce-00ec-4bdc-82cd-45a8889e43ff",
    "version": "0.5.4"
  },
  {
    "name": "ずんだもん",
    "styles": [{ "name": "ノーマル", "id": 1 }],
    "speaker_uuid": "388f246b-8c41-4ac1-8e2d-5d79f3ff56d9",
    "version": "0.5.4"
  }
]
```

**Comment by y-chan** [comment]
`情報をFastAPIのModelに入力していく（OpenAPI用の型付け）`をとりあえず引き受けようかなと思います。

**Comment by Hiroshiba** [comment]
@y-chan ありがとうございます！よろしくおねがいします！！

**Comment by Hiroshiba** [comment]
今日10/9の昼頃にスタイル音声合成が含まれるバージョン（0.7.0）をプレリリースしたいのですが、必須のタスクが残っているので協力を仰ぎたいです。
（といってもマイグレーションだけです。）

`0.7.0には必須ではないが必要なもの（0.8.0か0.7.1に含めたい）`も0.7.0に近い日程で出したいのですが、まだできていないのでこちらも協力を仰ぎたいです。
こちらの機能を実装するのは、音声スタイルは面白いから使ってほしい機能である一方、過去のボイロなどを見るに利用率がものすごく低いのをなんとかしたいためです。
瞬間的に盛り上がるのはスタイル追加のタイミングだと思うので、近い日程で出せればより盛り上がると考えています。

**Comment by Hiroshiba** [comment]
タスクが残っていますが、これは次のマイルストーン

- https://github.com/Hiroshiba/voicevox/issues/429 

の` CharactorInfoをエンジンから取って来るようにする`と同じなので、こちらのissueは閉じたいと思います。
難しいタスクでしたが達成できてよかったです！また次も頑張りましょう・・・！
