### ISSUE TITLE
読み変更するとイントネーションが文中っぽくなくなる

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#248]
## 内容

読み変更すると、読みが文中っぽくなくなります。

普通に「ボイスボックスがリリースされました」と入力した場合と、
「ボイスボックスが」の部分を読み変更で入力した場合の比較です
↓

https://user-images.githubusercontent.com/4987327/134188339-7427e1d5-7b19-453d-919e-998e18ca6068.mp4

２番めの方は「ボイスボックスが」の「が」が伸びていることがわかります。
これを１番目の方っぽくするとユーザーにとって違和感がないかなと思いました。

といっても長さが変わるだけなので、長さを変更するUIがあれば別に良いかなとも思います。

## その他

読み変更のロジックは「変更された読みの部分のtextを送り、その部分のAccentPhraseを置換する」ですが、こうするとtextが文頭・文末として送られるので、文中っぽい読み上げになりません。
ただ、textを変えた時点でAccentPhraseも変わるので、どこが変わったのかをちゃんと求めるロジックはかなり難しい気がします・・・。

**Comment by Segu-g** [comment]
`FETCH_ACCENT_PHRASES`でエンジンから得られる情報のうちこの操作で必要なのは、「アクセント句等の音声構造」と「モーラ長等の音素情報」のうち「アクセント句等の音声構造」だけであり、後者は文末の文脈として合成されるため不自然になってしまうのが問題です。なので「モーラ長等の音素情報」は`FETCH_ACCENT_PHRASES`を使って構造を求めたのちに`FETCH_MORA_DATA`を用いて文章全体で再計算したものをコピーすれば上手くいきそうな気がします。

**Comment by Hiroshiba** [comment]
あ、たしかに！！　完全に仰るとおりだと思います。
