### ISSUE TITLE
長い文章をコピペしたときに句点（。）で自動区切りする

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#25]
今のVOICEVOXは長い文章を入力したとき、同じテキスト欄に長文が入力されます。
句点で区切ると程よくバラけ、使いやすくなると考えています。

**Comment by scarletdango1204** [comment]
試しに追加

https://user-images.githubusercontent.com/59786459/128344497-ebae49e5-98a9-46bd-b4e4-b5352ae1ef04.mp4

**Comment by Hiroshiba** [comment]
マージされたので閉じます
