### ISSUE TITLE
ボリューム操作時にスクロールが同時に発生する

### ISSUE THREAD

**Issue by Oyaki122** [Hiroshiba/voicevox#272]
## 内容

![Videotogif](https://user-images.githubusercontent.com/42294158/134966390-1b52b844-8d5c-4322-bd1e-2028153ef8a6.gif)

画面が狭く、AudioInfo欄にスクロールバーが表示される場合、各ボリュームをマウスホイールで操作するとスクロールも発生してしまう

### Pros 良くなる点

ボリューム操作→スクロール→ボリューム操作→スクロール…を繰り返す必要がなくなる

### 実現方法

各ボリュームへマウスオーバーした際にイベントを発火し、スクロールを無効化する

## VOICEVOXのバージョン

0.6.1

## OSの種類/ディストリ/バージョン
- Windows 10 Pro 64bit 20H2

**Comment by Hiroshiba** [comment]
https://github.com/Hiroshiba/voicevox/pull/368 にて解決されました！
