### ISSUE TITLE
テキスト欄が全部消えてしまう

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#28]
VOICEVOX 0.1.1 だと、バックスペースキーを押し続けていると全てのテキスト欄が消えるため、ユーザーが何をすればいいかわからなくなります。
（右下のプラスボタンを押すと復帰できますが、気づきづらいです）

テキスト欄が全部消えてしまった場合にどうすればわかりやすいか議論、もしくは消せなくするのが手段にありそうです。

**Comment by scarletdango1204** [comment]
マウスオーバーで消せる機能が実装されてるっぽいので、バックスペースで空欄を消す操作が無くしてもいい気がします

**Comment by Hiroshiba** [comment]
解決したので閉じます。
