### ISSUE TITLE
プロジェクト変更の確認ダイアログが出ずに新規作成を実行できてしまう

### ISSUE THREAD

**Issue by uberded** [Hiroshiba/voicevox#322]
## 内容

プロジェクトを変更している状態で新規作成を実行すると、確認ダイアログなどが表示されずにプロジェクトが新規作成されてしまいます。
プロジェクトが変更された場合は新規作成を実行したときに確認ダイアログが出るべきです。

### Pros 良くなる点

誤ってプロジェクトを新規作成してしまっても対処できる。

### Cons 悪くなる点

特になし

### 実現方法

不明

## VOICEVOXのバージョン

0.7.0

## OSの種類/ディストリ/バージョン

Windows 10 Home 64bit (19043.1237)

**Comment by Hiroshiba** [comment]
解決されているのでcloseします！
