### ISSUE TITLE
設定画面が一部表示されない / 音声が保存できない

### ISSUE THREAD

**Issue by oov** [Hiroshiba/voicevox#331]
## 不具合の内容

設定画面が一部表示されない
音声に名前をつけて保存ができない

### 現象・ログ

設定項目の一部が表示されず、音声の再生はできるものの、保存系の機能が動作しないようです。

![image](https://user-images.githubusercontent.com/270909/136685163-e506476a-2e11-4436-ad71-f3b0b48055b6.png)

### 再現手順

`C:\Users\UserName\AppData\Roaming\voicevox` を削除してから起動
または新規インストール

## VOICEVOXのバージョン

0.7.0 と 0.7.1 のどちらでも発生
0.6.1 では発生せず

## OSの種類/ディストリ/バージョン

Windows 10 Home 21H1 19043.1237

**Comment by Hiroshiba** [comment]
報告ありがとうございます！
マージされたのでcloseします！
