### ISSUE TITLE
package-lockに差分が大量に含まれることを回避するには

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#37]
プルリクエストを眺めていると、package-lock.jsonに大量に差分が含まれていることがたまにあります。
どうやったら差分が発生しなくなるのか、初学者の多いリポジトリで差分を発生させない現実的な手法はあるのか知りたいです。

個人的にはpackage-lock.jsonをignoreしてもいいのではと思いますが、CIにとっては良くなさそうなので、どうすべきか詳しい方に聞きたいです。

**Comment by yamachu** [comment]
現状 [.node_version](https://github.com/Hiroshiba/voicevox/blob/0faaaa98b01cce036f03cc9e9bf5faae07dfa57e/.node-version) で指定していますが、nodenvなどの管理ソフトを使っていないユーザには特に意味を成しません。

そのためpackage.jsonのenginesフィールドに特定のNode.jsのバージョンを指定し、使われるnpmのバージョンも制限してしまうのがいいのではないかと思います。
Node.jsとnpmのバージョンがほぼ一定になった状態で再度npm iでlockファイルを生成しなおし、それを使うようにすれば差分は生じなくなると考えられます。

**Comment by sousuke0422** [comment]
package.jsonでバージョンの指定を厳密にしてpackage-lock.jsonを生成させないのも一つの手かもしれません
```diff
#例
- "vue": "^3.0.0",
+ "vue": "3.0.0",
```
```
#.npmrc
package-lock=false
```

**Comment by yamachu** [comment]
指定を厳密にするのは激しく同意です
しかしlockファイルを生成させないことに対してはあまりベターではないと思います。

というのも、明示的に使用しているパッケージのバージョンを固定しても、そのパッケージが内部的に依存しているパッケージのバージョンは固定出来ないからです。
何が起こるかというと、例えば at_types 系のパッケージのバージョンがインストールのタイミングで異なり、急にtscでトランスパイルが通らないみたいな。

**Comment by sousuke0422** [comment]
確かにパッケージが依存しているパッケージのバージョンが固定できないから何が起こるのか分からないのがデメリットですね

**Comment by Hiroshiba** [comment]
固定することの具体的な欠点、勉強になりました。

> そのためpackage.jsonのenginesフィールドに特定のNode.jsのバージョンを指定し、使われるnpmのバージョンも制限してしまうのがいいのではないかと思います。

僕はこの方法に賛成です。
package.jsonのengineを変更してnodeとnpmのバージョンが違った場合にエラーが出るようにし、READMEでバージョンを案内するのが良いと思います。

ちなみに僕が開発で使っていたnpmはほぼ最新版でした。

**Comment by yamachu** [comment]
現在voicevoxで使われているElectronはv12なので

https://www.electronjs.org/blog/electron-12-0
NodeのVersionを v14.16 > でenginesフィールドで固定してしまうのがいいのかなと思います。

ということで

- [ ] .node-version を 14.16.0 (もしくは14系の最新)
- [ ] enginesに `"node": ">=14.16 <15"` みたいのを追加

してNodeのバージョンを固定し、その状態でnpi installしてlockをキレイにしたものをpushでこのIssueは閉じれそうでうかね

**Comment by sousuke0422** [comment]
プルリクを開いてみました

**Comment by sousuke0422** [comment]
.node-versionを使用するために、ドキュメントでnodenv、nvm、nvsなどを使うように案内した方がいいでしょうか？

**Comment by Hiroshiba** [comment]
あ、.node-versionの使用は必須じゃなくても大丈夫です。
初学者の人でも１コマンドでいい感じの環境が作れると嬉しいですが、よくわからず・・・。

**Comment by sousuke0422** [comment]
nvsだとインストールしてnvs use auto叩くと.node-versionに書いてあるバージョンが入ります。
なのでそんな感じのことを書けばいいのではないでしょうか？

**Comment by Hiroshiba** [comment]
package.jsonのengineでバージョンを固定しつつ、最初にnpm ciしてもらう運用は賛成です。
実際そういう方針で動いているOSSなどがあれば参考にしたいです。

**Comment by Hiroshiba** [comment]
node.jsのバージョンを固定し、npmのバージョンもある程度揃えつつ、`npm run ci`を実行してもらう方針で一旦うまく回っていそうなので閉じます。
