### ISSUE TITLE
セル追加時に、現在の話速等のパラメータを受け継ぐ

### ISSUE THREAD

**Issue by noronoro56** [Hiroshiba/voicevox#383]
## 内容
現在の仕様では、＋ボタンや文章貼り付けなどで新しいセルが作成されると、パラメータがデフォルトにリセットされます。
同じキャラクターを継続して使う場合は同設定で利用される場合が多いはずなので、現在のセルのパラメータを引き継いだ方が使いやすいと考えました。

### Pros 良くなる点
操作感の向上

### Cons 悪くなる点
デフォルトのパラメータを基準に操作したい人もいるかも？
オンオフ機能も追加するべき？

## VOICEVOXのバージョン

0.7.4

## OSの種類/ディストリ/バージョン
*   Windows 10 Pro 64bit (19043.1288)

## その他
修正してみましたので、プルリクエストを出す予定です。
はじめてのOSS参加ですので、何か間違いがありましたらご指摘ください。

**Comment by noronoro56** [comment]
見様見真似なので不備があるかもしれませんが、プルリクエスト#384にオンオフ機能を作成しました。

**Comment by Hiroshiba** [comment]
解決されたのでcloseします
