### ISSUE TITLE
無声化切り替えをundo/redo可能にする

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#411]
## 内容

https://github.com/Hiroshiba/voicevox/pull/402 にて無声化の切り替えが実装されました！
現状はundo/redoの履歴が直感的ではないので、実験的機能になっています。
undo/redoを正しく組んで、実験的機能から本機能に移したいです。

### 実現方法

履歴が直感的でないのは、コマンドを２回実行しているためです。
ピッチのセットと、音素の切り替えの２つのコマンドを実行しています。
なのでこれらを１つにまとめると問題が解決するのですが、まとめること自体がちょっとややこしいです。

プルリクエストでの議論を一部引用します。

> なるほど･･･
`voicing`を切り替えたときになぜか`undo/redo`がおかしくなっていたのですが、`voicing`を切り替える処理と`F0`をセットする処理が別れているのが原因だと思います。
（１つの処理で２つのコマンドが登録されています。）
> 
> これを直すのはとても難しそうです。
先にあったように「`Mora`ごとに１つのコンポーネントを作る」ようにすれば解決するかもしれませんが･･･

https://github.com/Hiroshiba/voicevox/pull/402#discussion_r737705306

## その他

- https://github.com/Hiroshiba/voicevox/pull/402

**Comment by Yosshi999** [comment]
有声化する際に以前のピッチに戻すための[ここのwatch処理](https://github.com/Patchethium/voicevox/blob/40161b94b1baea0a3174f4cf3ecafc782c4fd56b/src/components/AudioParameter.vue#L119) 内のChangeValueが、無声化UNDOの際にも発火してしまうことが原因のような気がします。

**Comment by Segu-g** [comment]
発火してしまうというよりは、そこで発火せざるを得ない設計なのが問題ですね。Moraの有声化処理の為のコンポーネント（テキスト）がMora単位でない為、Mora毎のコンポーネントを持っているSliderを用いて、Historyを保持してしまっています。
無声化とビッチのヒストリーを保持するコンポーネントが同一であれば、変更のためのコマンドが1回で済むので壊れずに済むはずです

**Comment by Yosshi999** [comment]
AudioDetailから該当AudioParameterのlastPitchを拾えそうな気がしますがどうでしょうか

**Comment by Hiroshiba** [comment]
`lastPitch`が`AudioDetail`から取れれば、１つのCommandAction＆Mutationで無声化＆ピッチ設定ができるので、undo/redoできるようにできると思います！
