### ISSUE TITLE
CUIモードが欲しい

### ISSUE THREAD

**Issue by nmori** [Hiroshiba/voicevox#42]
・他のツールと簡単に連携させて動かすために、GUIをパスできる動作モードが欲しいです。
（もしくは、GUIを操作しなくてもコマンドラインで音声生成指示できる仕組みが欲しいです）
・この機能ができると、音声の自動バッチ生成なども行えるので、ツール連携しやすくなります。

**Comment by Hiroshiba** [comment]
VOICEVOXの音声合成エンジンはHTTPサーバーなので、リクエストを送ればCUIからも操作できます。
まだドキュメントは整えられていませんが、インターフェースを確認することができます。
VOICEVOXを起動した状態でlocalhost:50021/docsにアクセスしてみてください。
このあたりも参考になるかもしれません。 https://twitter.com/hiho_karuta/status/1423038523058233344
より詳しく知りたい場合は https://github.com/Hiroshiba/voicevox_engine にissueを建ててください。

このリポジトリはGUIソフトウェアを想定しており、対応できないためcloseします。

**Comment by nmori** [comment]
頂いた情報で進めてみます。ありがとうございます。
