### ISSUE TITLE
Mac：Windowのボタンの操作の改良

### ISSUE THREAD

**Issue by Apple-Yuki** [Hiroshiba/voicevox#427]
## 内容
<img width="123" alt="" src="https://user-images.githubusercontent.com/91584669/139593384-1f42ae39-c673-4a5e-963e-ec74d6f59182.png">

Macでのボタンは以下の動きするのでそれに合うようにしてほしい。

赤＝閉じる
黄色＝最小化
緑＝最大化

### Pros 良くなる点
Macのウインドウ操作と同じになり、Macユーザーが使いやすくなる

### Cons 悪くなる点

Windowsユーザー共通ならWindowsと若干動きが違うので戸惑う可能性あり

## VOICEVOXのバージョン

0.7.5

## OSの種類/ディストリ/バージョン

*   macOS 12 Monterey

**Comment by Hiroshiba** [comment]
たしかにmacのvscodeなども左上に赤や黄色のぼたんがあったので、合わせてもいいなと思いました。
ただこのUIにするとwindowsユーザーには使いづらくなってしまうので、macでのみこの挙動にすべきだと思います。

タイトルバーのコンポーネントはこちらにあります。
https://github.com/Hiroshiba/voicevox/blob/b77ba3aa87827dfd3eec07aff52db3c6a06db5ac/src/components/TitleBarButtons.vue

**Comment by PickledChair** [comment]
> たしかにmacのvscodeなども左上に赤や黄色のぼたんがあったので、合わせてもいいなと思いました。

ボタンが右上にあること自体は仕方がない気がしました。macOS でも、クロスプラットフォームのアプリケーションで「最大化・最小化・閉じる」ボタンが右上にあることは稀にあった気がします。仮にボタンを左上に移動するとして、現在の VOICEVOX の UI デザインだと、メニューバーの他の項目や左上の v マークをどこに配置するのかちょっと悩んでしまいそうです。

ところで、 @Apple-Yuki さんが指摘されているのは見た目の問題ではなく、「最大化・最小化・閉じる」ボタンに間違った機能が割り振られているバグのことだと思います。以下の動画で示しましたが、緑ボタンを押すと最小化され、黄色ボタンを押すと最大化する挙動になっており、緑ボタンと黄色ボタンの機能が逆になっています。緑で最大化、黄色で最小化（Dock に格納）が正しい挙動です。

https://user-images.githubusercontent.com/41382894/139802203-5d4d8567-be74-4a6f-aeff-4ec748d23bf0.mov

以下のソースコードを見ると、確かに `minimizeWindow()` と `maximizeWindow()` の指定が逆になっています。

https://github.com/Hiroshiba/voicevox/blob/b77ba3aa87827dfd3eec07aff52db3c6a06db5ac/src/components/TitleBarButtons.vue#L39-L64

**Comment by Hiroshiba** [comment]
あ、完全に勘違いしていました！！
ご指摘ありがとうございます、たしかに最小化と最大化が逆になっていそうです。

仰るとおりそちらの実装を入れ替えれば完了だと思います。
ちなみにデザインフレームワークのquasarに、mac風デザインのBarのサンプルがあるので、参考になるかもと思いました！
https://quasar.dev/vue-components/bar#styling
https://github.com/quasarframework/quasar/blob/82ba9059401c4324fe390d527a8faaa86a76d53f/docs/src/examples/QBar/MacOS.vue#L42-L44

**Comment by PickledChair** [comment]
わかりました！ やってみます。
