### ISSUE TITLE
自動ビルド時に製品版のリソースを取り込む

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#440]
## 内容

製品版のビルドに必要な話者情報やREADMEを別リポジトリに置きました。
https://github.com/Hiroshiba/voicevox_resource

これにより、エディターの自動ビルドでリソースを取り込み、（Artifactではなく）releasesにアップロードすることができるようになるはずです。

### Pros 良くなる点

github relesesへのリリースまで完全自動にできる

### 実現方法

現在、エディターに関してOSS版と製品版の違いは以下のとおりです

* public/characters以下の話者情報
  * `character_info`ディレクトリがほぼそのまま使えると思います
  * （今の実装ではファイル名に話者名が含まれていますが、話者名は任意文字列が来るので、[ENGINE側と同じ構成](https://github.com/Hiroshiba/voicevox_engine/tree/e068690fe216b74f851f267cb6810474c8e6e60a/speaker_info)にすると良いかもです）
* .exeがあるディレクトリのREADMEの有無
  * 製品版にだけ`README_SOFTWARE.txt`と`README_LIBRARY.txt`があります
  * `README_LIBRARY.txt`はキャラクターが増えると崩壊するので運用をやめて良さそうです
    * （ソフトウェア内やホームページで案内しているので消しても大丈夫です）
  * `README_SOFTWARE.txt`は`README.txt`に改名し、README.mdを.txtにリネームして配置しておけば良いと思います。
    * リッチな解決策としては、README.mdをhtmlにレンダリングした方が優しいかも
* public/policy.md
  * 製品版は、[voicevox_resource/editor](https://github.com/Hiroshiba/voicevox_resource/tree/cfa6e2883297bf0bcfb6a3d08ad78121bb204361/editor)にある`README.md`と`ACKNOWLEDGMENTS.md`を結合してpolicy.mdにしています

## VOICEVOXのバージョン

0.7.5

## その他

エンジンの方はビルド時に製品版のリソースを取り込むようになっています。
こちらのプルリクエストが参考になるかもです。

- https://github.com/Hiroshiba/voicevox_engine/pull/180

**Comment by y-chan** [comment]
ちょっとやってみようかなと思います。アサインしていただけると助かります。

**Comment by Hiroshiba** [comment]
おお！！ありがとうございます・・・！
