### ISSUE TITLE
サンプリングレートを変更しても、既存のAudioCellのサンプリングレートが変わらない

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#444]
## 不具合の内容

開発版の機能にある、設定でサンプリングレートを変えても、キャッシュが有るAudioCellのサンプリングレートは変わらなさそうです。
キャッシュヒットに問題があるかも。

### 再現手順

AudioCellの作って音声再生する。
サンプリングレートを変える。
もう一度再生する。

### 期待動作

サンプリングレートの異なる音声が再生される

## VOICEVOXのバージョン

0.?.0

## その他

パッとコードを確認した感じ、音声生成時のキャッシュIDと、音声再生時のキャッシュIDが異なるのが原因っぽかったです。

**Comment by y-chan** [comment]
エンジン側でリサンプリング対応したのに、これに対処するの忘れていました...
大分問題な気がするので、早急に対処します。

**Comment by Hiroshiba** [comment]
おっと、僕も忘れていました！
再起動でなんとかはなるのと、利用者はそこまで多くないのとで、hotfixじゃなくても良いかなと思いました。
別のhotfixがあればcherry pickします！
