### ISSUE TITLE
VOICEVOX 0.8.0 の Windows 用 GPU 版インストーラーでダウンロードが途中で失敗する

### ISSUE THREAD

**Issue by oov** [Hiroshiba/voicevox#448]
同じような症状が起こる方を探しています。

VOICEVOX 0.8.0 の GPU 版インストーラーを実行してダウンロードを始めると2番目のファイルでダウンロードが失敗し、
以下のようなダイアログが出るものの、何度再試行しても失敗し続ける、といった症状です。

![image](https://user-images.githubusercontent.com/270909/140622665-5892d524-9451-494d-811e-803050fcdd82.png)

今現在の GitHub 側でのレスポンスの挙動も若干怪しいのですが、
インストーラー側でも対策ができるかもしれないので、ご協力いただける方を探しています。

**Comment by oov** [comment]
分割ファイルをブラウザでダウンロードしてみると [voicevox-0.8.0-x64.nsis.7z.1](https://github.com/Hiroshiba/voicevox/releases/download/0.8.0/voicevox-0.8.0-x64.nsis.7z.1) だけ最初40秒ぐらい応答がなく、
その後で進捗ゲージが現れてダウンロードが進行します。

インストーラーにおいてはその最初の待ち時間の時点で
おそらく inetc::get プラグインの内部で使用されている WinInet でのデフォルトタイムアウト時間を超過しており、
ダウンロード失敗するという結果になっていると思われます。
その根拠としては、`regedit` で `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings` に
`ReceiveTimeout=60000`（60秒） の DWORD 値を追加すると、インストーラーが失敗しなくなるからです。
（参考: [Internet Explorerのタイムアウト時間を変更したい](https://www.itmedia.co.jp/help/tips/windows/w0682.html)）

このレジストリーの変更を行わなくとも IE11 でのダウンロードは失敗しないため、
おそらく WinInet でのデフォルト値には現在の IE11 とは関係のないタイムアウト値が用いられていると思われます。
そのため、インストーラー側でも明示的に指定することにより問題が回避できるようになると思われます。

**Comment by oov** [comment]
[VOICEVOX Web Setup 0.8.0.exe.zip](https://github.com/Hiroshiba/voicevox/files/7491288/VOICEVOX.Web.Setup.0.8.0.exe.zip)

https://github.com/Hiroshiba/voicevox/pull/449 の変更を含むインストーラーのプログラムです。
本来の手順で作成したものではないのでインストール前にエラーで弾かれますが、
ダウンロード処理の改善の確認ができます。

現在インストーラーの途中でダウンロードに失敗している方は
上記のインストーラーでダウンロードまでを進めてから中断し、
[本来のインストーラー](https://github.com/Hiroshiba/voicevox/releases/download/0.8.0/VOICEVOX.Web.Setup.0.8.0.exe)を上書きして改めて実行することでインストールを完了できると思われます。

**Comment by Hiroshiba** [comment]
報告ありがとうございます！

別の方からもGPU版インストーラがうまく動かない旨を聞きました。たぶん再現性のある問題だったと思います。

頂いたプルリクエストを適用し、バージョン0.8.1としてリリースする予定です！

**Comment by oov** [comment]
こちらこそ迅速な対応ありがとうございました。
お手数おかけしますがよろしくお願いいたします。
