### ISSUE TITLE
デフォルトショートカットキーの設定

### ISSUE THREAD

**Issue by nmori** [Hiroshiba/voicevox#45]
■リクエスト内容
　・各ボタンに ALT+●●　系のショートカット設定がほしい　
　　(たとえば、 再生なら(ALT+P)のようなもの）

■理由
　・キーボードベースで操作する場合に操作がしやすくなるため
　・スクリーンリーダのユーザ対応

■現状
　・TABを複数押す操作で移動。

**Comment by Hiroshiba** [comment]
良さそうです。

ElectronのショートカットキーはMenuを実装すれば実現可能だったと思います。
ちょうどメニュー機能のプルリクエスト https://github.com/Hiroshiba/voicevox/pull/38 を頂いているので、ここから進めれば実現できそうです。

プルリクエスト、お待ちしています。

**Comment by Hiroshiba** [comment]
https://github.com/Hiroshiba/voicevox/pull/63 で再生とかのショートカットキーが設定されました
