### ISSUE TITLE
開発版と製品版で同じ設定ファイルを使う関係で製品版が正常に起動しない

### ISSUE THREAD

**Issue by noronoro56** [Hiroshiba/voicevox#455]
## 不具合の内容
VOIVEVOX0.8.1zip版を起動時、画面がまっしろでテキスト欄が表示されない。
このとき、テキストのペーストや＋ボタンでのテキスト欄作成は動作しないが、テキストファイルの読み込みは正常に動作する。テキストファイルを読み込ませた後は、VOICEVOXの動作も正常に復旧する。
また、同条件下でVOICEVOX 0.7.5zip版は正常に起動する。
![2021年11月8日4時7分25秒イメージ8662](https://user-images.githubusercontent.com/92973480/140735291-7307f749-509a-4f2d-9f09-7398561db58c.png)

### 再現手順
不明

### 仮の対応
C:\Users\ユーザー名\AppData\Roaming\voicevox内のconfig.jsonを削除すると正常に動作した。

## VOICEVOXのバージョン

0.8.1

## OSの種類/ディストリ/バージョン
*   Windows 10 Pro 64bit 21H1(19043.1288)

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

これはおそらく開発版と製品版でキャラクターのUUIDが異なるために、辻褄が合わなくなって表示がバグるのが原因です。
キャラクターのUUIDを揃えたり、違っていても表示がバグらないようにもできますが、そもそも開発版と製品版で設定ファイル同じ場所の保存されているのが問題だと思います。
（実際、デバッグのとき結構不便でした・・・。）

開発版の設定保存ディレクトリをvoicevox-dev等にするのが良い解決策なのかなと思います。
ディレクトリの名前はの決定ロジックはこのあたりが参考になるかもです。
https://github.com/Hiroshiba/voicevox/issues/337

**Comment by Hiroshiba** [comment]
原因がわかっているので、issueのタイトルをバグの原因に変えさせて頂きます！
