### ISSUE TITLE
プロジェクト編集済み且つ未保存時にソフトウェアを終了する際に出す確認ダイアログの実装を変更する

### ISSUE THREAD

**Issue by madosuki** [Hiroshiba/voicevox#458]
## 内容

プロジェクト編集済みで保存をしていない状態でウィンドウを閉じる際に確認ダイアログが出るようになっています。
今の実装ではショートカットキーや閉じるボタンで能動的に終了させた時のみ実行されます。
予期せぬ終了に対しては無力なので確認処理を```before-quit```などのElectron側などのイベント内で実行するようにした方が良いと思います。

OSのシャットダウンとログアウトの際にウィンドウが閉じられる時でもダイアログが出せるようになるのが理想ですが、[https://www.electronjs.org/ja/docs/latest/api/app](https://www.electronjs.org/ja/docs/latest/api/app)を参照する限りではElectronの仕様上、Windows環境では現時点では難しそうです。

### Pros 良くなる点

予期せぬ終了への対応が改善される。

## VOICEVOXのバージョン

0.?.0

**Comment by Hiroshiba** [comment]
実装されたのでcloseします
