### ISSUE TITLE
ショートカットキーを変更後も変更前のキーが有効になっている

### ISSUE THREAD

**Issue by Uotsumi78a7** [Hiroshiba/voicevox#468]
## 不具合の内容
ショートカットキーを別のキーや未設定に変更した後も、変更前のキー設定が有効になっています。

### 現象・ログ
起動中に設定されていたことがあるどのキーを入力しても操作が実行されます。
複数回変更した場合は全て有効です。
ただし、異なる操作に同じキー設定をしたことがある場合は、現在設定されているキーが優先されます。
再起動すると、設定されているキーのみが有効になります。

### 再現手順
キー割り当てで「再生/停止」のショートカットキーを変更する。
編集画面で変更前に設定されていたキーを入力すると、音声合成と再生が実行される。

### 期待動作
現在設定されているショートカットキーのみが有効。

## VOICEVOXのバージョン

0.8.1

## OSの種類/ディストリ/バージョン
Windows 10 Home 64bit OSビルド19043.1348

**Comment by Hiroshiba** [comment]
報告ありがとうございます！

ショートカットキーのunbind処理はこのあたりで行おうとされていそうです。
https://github.com/Hiroshiba/voicevox/blob/989659a1ca08e4901c95c542993af63d51c8c184/src/store/setting.ts#L84-L106
パット見た感じoldがunbindされていそうなのですが、何か処理がおかしいのかも・・・？

**Comment by Patchethium** [comment]
```typescript
 const oldHotkey = state.hotkeySettings.find((value) => { 
   value.action == data.action;  // <--- I forgot a return here...
 }); 
```

Fix in #469
