### ISSUE TITLE
Electronのバージョンを上げる

### ISSUE THREAD

**Issue by MT224244** [Hiroshiba/voicevox#488]
## 内容

2021/11/16にElectron16がリリースされました https://www.electronjs.org/ja/blog/electron-16-0
これによりElectron12がサポート終了してしまったので、サポートされているバージョンに上げるべきだと思います

### Pros 良くなる点

特になし？

### Cons 悪くなる点

破壊的変更があった場合、実装を書き換える必要が出てくる可能性がある

## VOICEVOXのバージョン

0.?.0

**Comment by Hiroshiba** [comment]
上げたいですね！！
プルリクエスト頂けたらなんとなく動作検証してすぐマージしたいです。

関連しそうなissueのリンクも張っておきます。

- https://github.com/Hiroshiba/voicevox/issues/464

**Comment by koizuka** [comment]
とりあえず 13に上げるPR出します～

**Comment by koizuka** [comment]
なんかいけそうなので最新のv16にするやつもやってみます～
