### ISSUE TITLE
起動後右カルムが表示されない

### ISSUE THREAD

**Issue by Neko7sora** [Hiroshiba/voicevox#516]
## 不具合の内容

タイトルのとおりです

### 現象・ログ

https://user-images.githubusercontent.com/75793267/143586254-e76f9a00-1259-440d-9469-42356eb5461d.mp4

### 再現手順

起動後、右カルムを見る

### 期待動作

右カルムがちゃんと表示される

## VOICEVOXのバージョン

0.9.1

## OSの種類/ディストリ/バージョン

*   Windows 11 Home 64bit (22000.318)

**Comment by Hiroshiba** [comment]
issueありがとうございます！

おそらく右・下・左のカラムがどれも表示されないことがバグっぽい挙動とのことでissueを建てられたと思うのですが、こちらは最初にテキスト欄をクリックしてもらうための仕様になります。
違っていたり、更に意見があればコメントやopenし直しをお願いします！
