### ISSUE TITLE
一部の音声が書き出されない場合がある（らしい）

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#52]
ツイッターを見ていると、音声が一部だけ保存されないと困っている人を数人見かけました。
ソフトウェアを再起動するとうまく保存されるらしいです。

参考
https://twitter.com/beyounya/status/1424260772121571330
https://twitter.com/beyounya/status/1424263431952076813
https://twitter.com/beyounya/status/1424314338873987073

**Comment by nico-soin** [comment]
以下の文で、0.3.1でも再現します。

佐賀県・長崎県・福岡県・広島県に特別警報

https://www.nicovideo.jp/watch/sm39183196

**Comment by Hiroshiba** [comment]
@nico-soin ご報告ありがとうございます。
そちらの挙動はバグではなく、現段階の仕様になります。
（修正したいのですがディープラーニングからやり直しになるため時間がかかっています）

「書き出し」時に音声ファイルが書き出されない減少に遭遇された際はぜひまたご報告ください。

**Comment by Hiroshiba** [comment]
とりあえずエラーハンドリングが追加されたので一旦閉じ https://github.com/Hiroshiba/voicevox/pull/189
