### ISSUE TITLE
パラメータの引き継ぎが行われていない？

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#522]
## 不具合の内容

右のパネル（AudioInfo）の情報はセル追加時に引き継がれるはずなのですが、AuioItemの追加ロジックが変わったのか、引き継がれていない気がします。

### 再現手順

https://user-images.githubusercontent.com/4987327/143604380-a74a2b1f-9bde-4823-8544-091f8f54c584.mp4

## VOICEVOXのバージョン

0.9.0

## その他

hotfixしたいので、まだ0.10.0が出ていない場合は`release-0.9`ブランチから修正を作成し、`release-0.9`に向けてプルリクエストを頂けると嬉しいです。

**Comment by Segu-g** [comment]
動画を見るとAudioItemの生成タイミング(GENERATE_AUDIO_ITEM)でのqueryの取得が上手くいっていないように思えます．(パラメータの引継ぎはAudioItem生成時に行われるのでこの時にqueryを生成できないとコピーが行われません)
もしくは，engineStateがREADYでない状態になっているとかでしょうか....?
私の環境では再現が出来ないのでもっと詳しい発生環境をお聞きしたいです．

**Comment by y-chan** [comment]
> engineStateがREADYでない状態になっているとかでしょうか....?

私はこの状況なら再現できました。
この問題はニコ生で発覚したと存じていますが、ニコ生での状況的に、雨晴はうさん入りのエンジンを裏で動かしているものだったと思います。

なので、何の問題もなく、ただただ正しい挙動をしたまでだと思います。

**Comment by Hiroshiba** [comment]
おっと、なるほどです！！
特に大きな問題ではなさそうなので一旦closeしたいと思います。
