### ISSUE TITLE
txtファイルを書き出す機能をデフォルトでオフにする

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#529]
## 内容

txtファイルを書き出しする機能がデフォルトでONになっています。
音声合成ソフトを最もよくわからないのは初心者で、音声合成ソフトウェアの初心者にとってはテキスト書き出しは無いほうが混乱が少ないと思っています。

ただaviutl＋かんしくんなどを使っているとおそらく必要な機能となっており、
多くのユーザーが参考にするサイトで、「txtファイルを書き出しをONにしてください」という説明が無いのであればちょっと混乱するかもしれません。

解決は一瞬ですが、よかったら意見がほしいです。

### Pros 良くなる点

初心者が混乱しない

### Cons 悪くなる点

aviutlを使う初心者向けに説明されたサイトでONにする工程がない場合に初心者が迷う

## VOICEVOXのバージョン

0.?.0

## その他

意見があれば募集中です

（@oov さんのご意見伺いたいです）

**Comment by oov** [comment]
デフォルトでオフにすることについては特に異論はありません。

ただ `テキストを書き出すと混乱する` というのはよくわかりませんでした。
そもそもこれについては変更に際しての主たる理由ではないように思います。
（言葉を選んだ結果だとは思っております）

この変更は [UX・UIデザインの方針](https://github.com/Hiroshiba/voicevox/blob/main/docs/UX%E3%83%BBUI%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%81%AE%E6%96%B9%E9%87%9D.md) にある `あってもなくても良いような機能はなるべく目立たない UI に` という方針に基づき、
「ソフトウェアをシンプルな状態に保つため、全ユーザーにとって必須ではない機能をデフォルトでオフにしたい」
というのが本当の理由ではありませんか？

こちらでしたら大いに賛成できます。
全ユーザーが音声保存時にどうしても絶対に必要になるのは「音声ファイル」だけであり、
これには想像や推測は含まれていないからです。

----

プログラム面についてですが、この機能を実装するための PR をお送りした https://github.com/Hiroshiba/voicevox/pull/8 の当時は設定画面のようなものが一切なく、
メインメニューすらもこの時点では存在していなかったので直接テキストファイルの保存機能を実装していましたが、
設定を変更可能になっている現在においてはデフォルトでオフでも特に問題ないと思います。

利用者は設定を変えれば以前と全く同じように使えるので変更による影響はほぼなく、
ローカルに今までのバージョンでの設定が保存されている場合はデフォルト変更の影響を受けることもないでしょうから、
実際の影響範囲は更に小さくなるはずです。

リリース時に変更した旨と確たる根拠が添えられていれば、問題はないと思います。

**Comment by Hiroshiba** [comment]
ご意見ありがとうございます！
たしかに、シンプルさを保ちたいというのが一番の理由になりそうです。

ではデフォルト値を変更し、リリース時にツイートで案内したいと思います！

**Comment by Hiroshiba** [comment]
プルリクエストの形にしようと思っていたのですが、間違えてmasterにコミットしてしまいました。

- https://github.com/Hiroshiba/voicevox/commit/dbe7e9529a6230a356e7085526207fcfef1e4671

問題等あればまた修正したいと思います！
