### ISSUE TITLE
メニューもVueにする

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#75]
現状だとメニュー（画面の上部にあるバー）はElectronのものを使っている。
Electronの仕様上、これだとVueとの連携にIPC通信を挟む必要があり、処理が煩雑になる。
（例えば音声保存中にdisableにするだけで[この規模](https://github.com/Hiroshiba/voicevox/pull/71/files)の変更が必要）

VSCodeを見ると、ElectronのメニューではなくHTMLを使っているように見える。
これと同じように、Vueのコンポーネントで置き換えるとエレガントかもしれない。

![image](https://user-images.githubusercontent.com/4987327/129231229-8594be02-a6ef-44c0-8938-11d939349a34.png)

UIライブラリQuasarを見ると、Toolbarが良い感じかも。
https://quasar.dev/vue-components/toolbar

**Comment by Segu-g** [comment]
VSCodeや現在のメニューバーに近いデザインだとToolbarよりbarの方が近そうです。
https://quasar.dev/vue-components/bar
