### ISSUE TITLE
テストを書いてCIを設定したい

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#90]
バージョン0.3.0アップデートの際に、簡単に気づけそうなバグがあった状態でリリースされてしまいました。
https://github.com/Hiroshiba/voicevox_engine/pull/15/files#diff-d6af0459a37d985953d7040c14f53feb3b9cc9e58b543aa3c2b80256d276c5e0

機能が増えているのでテストがないと不具合に気づきにくくなっていそうなので、そろそろテストがほしいところです。

**Comment by Hiroshiba** [comment]
バージョン0.4.0のときも（自分の）人為的ミスでバグを埋め込んでしまいました・・・。
切実にテストがほしいと感じました。やってもいいよという方がいらっしゃったらぜひお願いしたいです。

**Comment by raa0121** [comment]
#164 で完了してないでしょうか？

**Comment by Hiroshiba** [comment]
たしかに、テストは完備されていませんがCIは設定されたので、いったん閉じてテストを実装していく旨のissueを作り直したほうが良いかもです。

**Comment by raa0121** [comment]
どちらにするかは、おまかせします。
やりやすい方で良いと思います。

**Comment by Hiroshiba** [comment]
ではいったん閉じます。  #182
